
  CREATE TABLE "THH_C4C"."T_FRM_CELLTXT"
   (	"CLASSTYPE" VARCHAR2(255),
	"FMCT_C4C_ID" VARCHAR2(4000),
	"FMCT_CRTD" DATE,
	"FMCT_LAS_ACT" NUMBER(10,0),
	"FMCT_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"FMCT_LAS_ACT_TIM" DATE,
	"FMCT_OBJ_STT" NUMBER(10,0),
	"FMCT_VERS" NUMBER(19,0) DEFAULT 0,
	"FMCT_VSBT" NUMBER(10,0),
	"FMCT_DLTDDT" DATE,
	"FMCT_LAS_ACT_BY" NUMBER(19,0),
	"FMCT_ORIGCRTR" NUMBER(19,0),
	"FMCT_ORIGCRTRLOGDIN" NUMBER(19,0),
	"FMCT_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"FMCT_UNIVID" VARCHAR2(4000),
	"FMCT_ROW_NMBR" NUMBER(10,0),
	"FMCT_CLMNNMBR" NUMBER(10,0),
	"FMCT_TXT" VARCHAR2(4000),
	"FMCT_ID" NUMBER(19,0),
	"FMCT_RSPE" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_MEMBDGISBASE"
   (	"CLASSTYPE" VARCHAR2(255),
	"MBDB_C4C_ID" VARCHAR2(4000),
	"MBDB_CRTD" DATE,
	"MBDB_LAS_ACT" NUMBER(10,0),
	"MBDB_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"MBDB_LAS_ACT_TIM" DATE,
	"MBDB_OBJ_STT" NUMBER(10,0),
	"MBDB_VERS" NUMBER(19,0) DEFAULT 0,
	"MBDB_VSBT" NUMBER(10,0),
	"MBDB_DLTDDT" DATE,
	"MBDB_LAS_ACT_BY" NUMBER(19,0),
	"MBDB_ORIGCRTR" NUMBER(19,0),
	"MBDB_ORIGCRTRLOGDIN" NUMBER(19,0),
	"MBDB_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"MBDB_UNIVID" VARCHAR2(4000),
	"MBDB_RESNOR_CMMT" VARCHAR2(4000),
	"MBDB_ID" NUMBER(19,0),
	"CFDS_ID" NUMBER(19,0),
	"MDSS_STRTDT" DATE,
	"MDSS_END_DT" DATE,
	"MDSS_RSLVDT" DATE,
	"MDSS_RSTNCMMT" VARCHAR2(4000),
	"MDSS_IS_PMRYDGIS" NUMBER(1,0),
	"MDSS_IS_REQ_AND_PERFPROVSAME" NUMBER(1,0),
	"MDSS_IS_SLTD" NUMBER(1,0),
	"MDSS_IS_ERR" NUMBER(1,0) DEFAULT 0,
	"MDSS_SRC_USR_NAM" VARCHAR2(4000),
	"MDSS_ERR_TXT" VARCHAR2(4000),
	"MDSS_WKFWISTCID" VARCHAR2(4000),
	"MDSS_CNV_ID" VARCHAR2(4000),
	"MDSS_OWNRCHNDFLAG" NUMBER(1,0),
	"MDSS_OWNRCHNDCNT" NUMBER(10,0),
	"MDSS_SRC__SRC_TYP" NUMBER(10,0),
	"MDSS_ID" NUMBER(19,0),
	"CBDG_ID" NUMBER(19,0),
	"UMAD_ID" NUMBER(19,0),
	"CMDI_ID" NUMBER(19,0),
	"UMDS_ID" NUMBER(19,0),
	"MDSS_RFNGWKFWTSK" NUMBER(19,0),
	"MDSS_PRVSRFNGTSK" NUMBER(19,0),
	"MDSS_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"MDSS_OWNR" NUMBER(19,0),
	"MDSS_PRVSOWNR" NUMBER(19,0),
	"MDSS_PRVSSNDR" NUMBER(19,0),
	"MDSS_PRVSOWNRPRMN" NUMBER(19,0),
	"MDSS_TNFR" NUMBER(19,0),
	"MDSS_PRVSTNFR" NUMBER(19,0),
	"MDSS_SRC__ASMTCARECALC" NUMBER(19,0),
	"MDSS_SRC__PAT_ID_QRY" NUMBER(19,0),
	"CMDI_CM_BASE" NUMBER(19,0),
	"CFDS_CM_TMPT" NUMBER(19,0),
	"CFDS_THE_BRNCACT" NUMBER(19,0),
	"MBDB_DGIS" NUMBER(19,0),
	"CFDS_SENTASMT" NUMBER(19,0),
	"MDSS_CAUDBY" NUMBER(19,0),
	"MDSS_TAKNASMTCC" NUMBER(19,0),
	"MDSS_MEMB" NUMBER(19,0),
	"CBDG_MDCLCLM" NUMBER(19,0),
	"UMAD_UMBS" NUMBER(19,0),
	"CFDS_AMTN" NUMBER(19,0),
	"MBDB_CSTMFLDS" NUMBER(19,0),
	"UMDS_DGISUM_EVNT" NUMBER(19,0),
	"UMDS_SNP" NUMBER(19,0),
	"MDSS_GRP" NUMBER(19,0),
	"MPDS_PRBLM_DSCRP" VARCHAR2(4000),
	"MPDS_PRBLM_NAME" VARCHAR2(4000),
	"MPDS_PRBLM_CLSRRSN" NUMBER(19,0),
	"MPDS_PRBLM_STATUS" NUMBER(19,0),
	"MPDS_PRBLM_SRC" NUMBER(19,0),
	"MPDS_PRBLM_SRC_ID" NUMBER(19,0),
	"MPDS_PRBLM_COMMENT" VARCHAR2(4000),
	"MPDS_PRBLM_GNRTD_FRM_SRC_ID" NUMBER(19,0),
	"CFPRBLMDS_THE_BRNCACT" NUMBER(19,0),
	"CFPRBLMDS_ID" NUMBER(19,0),
	"CFPRBLMDS_SENTASMT" NUMBER(19,0),
	"PRBLM_CAUDBY" NUMBER(19,0),
	"PRBLM_TAKNASMTCC" NUMBER(19,0),
	"CFPRBLMDS_AMTN" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_QTN"
   (	"CLASSTYPE" VARCHAR2(255),
	"QTN_C4C_ID" VARCHAR2(4000),
	"QTN_CRTD" DATE,
	"QTN_LAS_ACT" NUMBER(10,0),
	"QTN_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"QTN_LAS_ACT_TIM" DATE,
	"QTN_OBJ_STT" NUMBER(10,0),
	"QTN_VERS" NUMBER(19,0) DEFAULT 0,
	"QTN_VSBT" NUMBER(10,0),
	"QTN_DLTDDT" DATE,
	"QTN_LAS_ACT_BY" NUMBER(19,0),
	"QTN_ORIGCRTR" NUMBER(19,0),
	"QTN_ORIGCRTRLOGDIN" NUMBER(19,0),
	"QTN_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"QTN_UNIVID" VARCHAR2(4000),
	"QTN_QTN_TXT" VARCHAR2(4000),
	"QTN_RSPEFRMT" VARCHAR2(4000),
	"QTN_MULTMUSTSEL" NUMBER(1,0),
	"QTN_MULTMX_SLTD" NUMBER(10,0),
	"QTN_ORD" NUMBER(10,0),
	"QTN_PRMT" NUMBER(1,0),
	"QTN_TXT_FRMT" VARCHAR2(4000),
	"QTN_VAL_FRMT" VARCHAR2(4000),
	"QTN_RSPETYP" NUMBER(10,0),
	"QTN_IN_POOL" NUMBER(1,0),
	"QTN_OTXTLMIT" NUMBER(10,0),
	"QTN_CHCEAS_LIST" NUMBER(1,0),
	"QTN_WGHT" FLOAT(126),
	"QTN_MNTY" NUMBER(1,0),
	"QTN_ID" NUMBER(19,0),
	"QTN_TYP_SBTY" NUMBER(19,0),
	"QTN_STTSFMLS" NUMBER(19,0),
	"QTN_SKIPFRMA" NUMBER(19,0),
	"QTN_REP_FRMA" NUMBER(19,0),
	"QTN_SCLB" NUMBER(19,0),
	"QTN_ORIG" NUMBER(19,0),
	"QTN_QTN_FRMA" NUMBER(19,0),
	"QTN_TSK_FRMA" NUMBER(19,0),
	"QTN_ASMTCC" NUMBER(19,0),
	"QTN_ALM_FRMA" NUMBER(19,0),
	"QTN_DGESFRMA" NUMBER(19,0),
	"QTN_CAREBEANFRMA" NUMBER(19,0),
	"QTN_WGHTFRMA" NUMBER(19,0),
	"QTN_PRBLMFRMA" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_REP"
   (	"CLASSTYPE" VARCHAR2(255),
	"RPT_C4C_ID" VARCHAR2(4000),
	"RPT_CRTD" DATE,
	"RPT_LAS_ACT" NUMBER(10,0),
	"RPT_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"RPT_LAS_ACT_TIM" DATE,
	"RPT_OBJ_STT" NUMBER(10,0),
	"RPT_VERS" NUMBER(19,0) DEFAULT 0,
	"RPT_VSBT" NUMBER(10,0),
	"RPT_DLTDDT" DATE,
	"RPT_LAS_ACT_BY" NUMBER(19,0),
	"RPT_ORIGCRTR" NUMBER(19,0),
	"RPT_ORIGCRTRLOGDIN" NUMBER(19,0),
	"RPT_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"RPT_UNIVID" VARCHAR2(4000),
	"RPT_CAT" NUMBER(10,0),
	"RPT_TXT" VARCHAR2(4000),
	"RPT_ID" NUMBER(19,0),
	"RPT_TAKNASMTCC" NUMBER(19,0),
	"RPT_CAUDBY" NUMBER(19,0),
	"RPT_THE_BRNCACT" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_RSPE"
   (	"CLASSTYPE" VARCHAR2(255),
	"RESP_C4C_ID" VARCHAR2(4000),
	"RESP_CRTD" DATE,
	"RESP_LAS_ACT" NUMBER(10,0),
	"RESP_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"RESP_LAS_ACT_TIM" DATE,
	"RESP_OBJ_STT" NUMBER(10,0),
	"RESP_VERS" NUMBER(19,0) DEFAULT 0,
	"RESP_VSBT" NUMBER(10,0),
	"RESP_DLTDDT" DATE,
	"RESP_LAS_ACT_BY" NUMBER(19,0),
	"RESP_ORIGCRTR" NUMBER(19,0),
	"RESP_ORIGCRTRLOGDIN" NUMBER(19,0),
	"RESP_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"RESP_UNIVID" VARCHAR2(4000),
	"RESP_TXT" VARCHAR2(4000),
	"RESP_NMBR" FLOAT(126),
	"RESP_SCOR" FLOAT(126),
	"RESP_ID" NUMBER(19,0),
	"RESP_QTN" NUMBER(19,0),
	"RESP_TAKNASMTCC" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_RSPECHCS"
   (	"CLASSTYPE" VARCHAR2(255),
	"RPCH_C4C_ID" VARCHAR2(4000),
	"RPCH_CRTD" DATE,
	"RPCH_LAS_ACT" NUMBER(10,0),
	"RPCH_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"RPCH_LAS_ACT_TIM" DATE,
	"RPCH_OBJ_STT" NUMBER(10,0),
	"RPCH_VERS" NUMBER(19,0) DEFAULT 0,
	"RPCH_VSBT" NUMBER(10,0),
	"RPCH_DLTDDT" DATE,
	"RPCH_LAS_ACT_BY" NUMBER(19,0),
	"RPCH_ORIGCRTR" NUMBER(19,0),
	"RPCH_ORIGCRTRLOGDIN" NUMBER(19,0),
	"RPCH_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"RPCH_UNIVID" VARCHAR2(4000),
	"RPCH_ID" NUMBER(19,0),
	"RPCH_RSPE" NUMBER(19,0),
	"RPCH_CHCS" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_SENTCAREBEAN"
   (	"CLASSTYPE" VARCHAR2(255),
	"STCB_C4C_ID" VARCHAR2(4000),
	"STCB_CRTD" DATE,
	"STCB_LAS_ACT" NUMBER(10,0),
	"STCB_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"STCB_LAS_ACT_TIM" DATE,
	"STCB_OBJ_STT" NUMBER(10,0),
	"STCB_VERS" NUMBER(19,0) DEFAULT 0,
	"STCB_VSBT" NUMBER(10,0),
	"STCB_DLTDDT" DATE,
	"STCB_LAS_ACT_BY" NUMBER(19,0),
	"STCB_ORIGCRTR" NUMBER(19,0),
	"STCB_ORIGCRTRLOGDIN" NUMBER(19,0),
	"STCB_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"STCB_UNIVID" VARCHAR2(4000),
	"STCB_NAM" VARCHAR2(4000),
	"STCB_PRUS" VARCHAR2(4000),
	"STCB_SNDRSPCDDTS" NUMBER(1,0),
	"STCB_WLCMTXT" VARCHAR2(4000),
	"STCB_RCMD" NUMBER(1,0),
	"STCB_SENT" DATE,
	"STCB_SRTD" DATE,
	"STCB_TMTD" DATE,
	"STCB_OTCM" NUMBER(10,0),
	"STCB_LAS_RTEDTO_GKPRAT" DATE,
	"STCB_LAS_GKPRACT_AT" DATE,
	"STCB_GKPROTCM" NUMBER(10,0),
	"STCB_WKFWISTCID" VARCHAR2(4000),
	"STCB_CNV_ID" VARCHAR2(4000),
	"STCB_OWNRCHNDFLAG" NUMBER(1,0),
	"STCB_OWNRCHNDCNT" NUMBER(10,0),
	"STCB_SRC__SRC_TYP" NUMBER(10,0),
	"STCB_ID" NUMBER(19,0),
	"STCB_ORIGRCPT" NUMBER(19,0),
	"STCB_LAS_GKPR" NUMBER(19,0),
	"STCB_RFNGWKFWTSK" NUMBER(19,0),
	"STCB_PRVSRFNGTSK" NUMBER(19,0),
	"STCB_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"STCB_OWNR" NUMBER(19,0),
	"STCB_PRVSOWNR" NUMBER(19,0),
	"STCB_PRVSSNDR" NUMBER(19,0),
	"STCB_PRVSOWNRPRMN" NUMBER(19,0),
	"STCB_TNFR" NUMBER(19,0),
	"STCB_PRVSTNFR" NUMBER(19,0),
	"STCB_SRC__ASMTCARECALC" NUMBER(19,0),
	"STCB_SRC__PAT_ID_QRY" NUMBER(19,0),
	"STCB_AFFN_UM_EVNTREQT" NUMBER(19,0),
	"STCB_AFFN_UM_EXTN" NUMBER(19,0),
	"STCB_AFFN_PVDR" NUMBER(19,0),
	"STCB_AFFN_CM" NUMBER(19,0),
	"STCB_AFFN_MEMB" NUMBER(19,0),
	"STCB_AFFN_UM_EVNT" NUMBER(19,0),
	"STCB_CAUDBY" NUMBER(19,0),
	"STCB_CSTMFLDS" NUMBER(19,0),
	"STCB_GRP" NUMBER(19,0),
	"STCB_CAREBEAN" NUMBER(19,0),
	"STCB_TAKNASMTCC" NUMBER(19,0),
	"STCB_TAKNASMTCC_BASE" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_SENTTSK"
   (	"CLASSTYPE" VARCHAR2(255),
	"SETK_C4C_ID" VARCHAR2(255),
	"SETK_CRTD" DATE,
	"SETK_LAS_ACT" NUMBER(10,0),
	"SETK_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"SETK_LAS_ACT_TIM" DATE,
	"SETK_OBJ_STT" NUMBER(10,0),
	"SETK_VERS" NUMBER(19,0) DEFAULT 0,
	"SETK_VSBT" NUMBER(10,0),
	"SETK_DLTDDT" DATE,
	"SETK_LAS_ACT_BY" NUMBER(19,0),
	"SETK_ORIGCRTR" NUMBER(19,0),
	"SETK_ORIGCRTRLOGDIN" NUMBER(19,0),
	"SETK_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"SETK_UNIVID" VARCHAR2(4000),
	"SETK_DDLNALRTRCPT" NUMBER(10,0),
	"SETK_TSK_NAM" VARCHAR2(4000),
	"SETK_TSK_DSCN" VARCHAR2(4000),
	"SETK_DRTN_AMNT" NUMBER(10,0),
	"SETK_DRTN_UNIT" NUMBER(10,0),
	"SETK_RMDRPRCDWTH__AMNT" NUMBER(10,0),
	"SETK_RMDRPRCDWTH__UNIT" NUMBER(10,0),
	"SETK_PRNL" NUMBER(1,0),
	"SETK_SUBJ" VARCHAR2(4000),
	"SETK_CMMT" VARCHAR2(4000),
	"SETK_CMPD" DATE,
	"SETK_RMDRTIM_ORGN" NUMBER(10,0),
	"SETK_DDLNTIM_BLCK_AMNT" NUMBER(10,0),
	"SETK_DDLNTIM_BLCK_UNIT" NUMBER(10,0),
	"SETK_CNCLCMMT" VARCHAR2(4000),
	"SETK_SENT" DATE,
	"SETK_SRTD" DATE,
	"SETK_TMTD" DATE,
	"SETK_OTCM" NUMBER(10,0),
	"SETK_WKFWISTCID" VARCHAR2(4000),
	"SETK_CNV_ID" VARCHAR2(4000),
	"SETK_OWNRCHNDFLAG" NUMBER(1,0),
	"SETK_OWNRCHNDCNT" NUMBER(10,0),
	"SETK_SRC__SRC_TYP" NUMBER(10,0),
	"SETK_TSK_TIMG_DDLN_DT" DATE,
	"SETK_TSK_TIMG_DDLN_TIM_IN_DY" NUMBER(10,0),
	"SETK_TSK_TIMG_DDLNACT" NUMBER(10,0),
	"SETK_TSK_TIMG_STRTDT" DATE,
	"SETK_TSK_TIMG_SCLDAT" NUMBER(10,0),
	"SETK_TSK_TIMG_SNLTTSK" NUMBER(1,0),
	"SETK_TSK_TIMG_SNLTDT" DATE,
	"SETK_TSK_TIMG_SNLTACT" NUMBER(10,0),
	"SETK_TSK_TIMG_DDLNBFR_NXT_IRTN" NUMBER(1,0),
	"SETK_TSK_TIMG_DDLNSLTN" NUMBER(10,0),
	"SETK_TSK_TIMG_SCLD" NUMBER(1,0),
	"SETK_ID" NUMBER(19,0),
	"SCBT_STRTTIM_BLCK_AMNT" NUMBER(10,0),
	"SCBT_STRTTIM_BLCK_UNIT" NUMBER(10,0),
	"SCBT_NMBR" NUMBER(10,0),
	"SCBT_AFT_EACHISTC" NUMBER(1,0),
	"SCBT_ID" NUMBER(19,0),
	"SETK_AFFN_UM_EVNTREQT" NUMBER(19,0),
	"SETK_AFFN_UM_EXTN" NUMBER(19,0),
	"SETK_AFFN_PVDR" NUMBER(19,0),
	"SETK_AFFN_CM" NUMBER(19,0),
	"SETK_AFFN_MEMB" NUMBER(19,0),
	"SETK_AFFN_UM_EVNT" NUMBER(19,0),
	"SETK_ORIGRCPT" NUMBER(19,0),
	"SETK_RFNGWKFWTSK" NUMBER(19,0),
	"SETK_PRVSRFNGTSK" NUMBER(19,0),
	"SETK_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"SETK_OWNR" NUMBER(19,0),
	"SETK_PRVSOWNR" NUMBER(19,0),
	"SETK_PRVSSNDR" NUMBER(19,0),
	"SETK_PRVSOWNRPRMN" NUMBER(19,0),
	"SETK_TNFR" NUMBER(19,0),
	"SETK_PRVSTNFR" NUMBER(19,0),
	"SETK_SRC__ASMTCARECALC" NUMBER(19,0),
	"SETK_SRC__PAT_ID_QRY" NUMBER(19,0),
	"SETK_CAUDBY" NUMBER(19,0),
	"SETK_CSTMFLDS" NUMBER(19,0),
	"SETK_CNCLRESN" NUMBER(19,0),
	"SETK_GRP" NUMBER(19,0),
	"SCBT_CAREBEAN" NUMBER(19,0),
	"SCBT_CAREBEANTSK" NUMBER(19,0),
	"SETK_TSK_TYP" NUMBER(19,0),
	"SETK_RETNPTRN" NUMBER(19,0),
	"SETK_TMPT" NUMBER(19,0),
	"SETK_TAKNASMTCC_BASE" NUMBER(19,0),
	"SETK_UM_BASE" NUMBER(19,0),
	"SETK_RESCHEDULE_REASON" NUMBER(19,0),
	"SETK_RESCHEDULE_COMMENT" VARCHAR2(4000)
   ) ;


  CREATE TABLE "THH_C4C"."T_STTS"
   (	"CLASSTYPE" VARCHAR2(255),
	"STA_C4C_ID" VARCHAR2(4000),
	"STA_CRTD" DATE,
	"STA_LAS_ACT" NUMBER(10,0),
	"STA_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"STA_LAS_ACT_TIM" DATE,
	"STA_OBJ_STT" NUMBER(10,0),
	"STA_VERS" NUMBER(19,0) DEFAULT 0,
	"STA_VSBT" NUMBER(10,0),
	"STA_DLTDDT" DATE,
	"STA_LAS_ACT_BY" NUMBER(19,0),
	"STA_ORIGCRTR" NUMBER(19,0),
	"STA_ORIGCRTRLOGDIN" NUMBER(19,0),
	"STA_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"STA_UNIVID" VARCHAR2(4000),
	"STA_PYSL" NUMBER(10,0),
	"STA_EMTN" NUMBER(10,0),
	"STA_CMPC" NUMBER(10,0),
	"STA_FINC" NUMBER(10,0),
	"STA_ID" NUMBER(19,0),
	"STA_CAUDBY" NUMBER(19,0),
	"STA_TAKNASMTCC" NUMBER(19,0),
	"STA_THE_BRNCACT" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."T_TAKNASMTCC_BASE"
   (	"CLASSTYPE" VARCHAR2(255),
	"TACB_C4C_ID" VARCHAR2(4000),
	"TACB_CRTD" DATE,
	"TACB_LAS_ACT" NUMBER(10,0),
	"TACB_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"TACB_LAS_ACT_TIM" DATE,
	"TACB_OBJ_STT" NUMBER(10,0),
	"TACB_VERS" NUMBER(19,0) DEFAULT 0,
	"TACB_VSBT" NUMBER(10,0),
	"TACB_DLTDDT" DATE,
	"TACB_LAS_ACT_BY" NUMBER(19,0),
	"TACB_ORIGCRTR" NUMBER(19,0),
	"TACB_ORIGCRTRLOGDIN" NUMBER(19,0),
	"TACB_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"TACB_UNIVID" VARCHAR2(4000),
	"TACB_SCOR" FLOAT(126),
	"TACB_DSCMACPD" NUMBER(1,0),
	"TACB_ID" NUMBER(19,0),
	"CCTR_CMPDAT" DATE,
	"CCTR_ID" NUMBER(19,0),
	"STAT_WKFWISTCID" VARCHAR2(4000),
	"STAT_CNV_ID" VARCHAR2(4000),
	"STAT_OWNRCHNDFLAG" NUMBER(1,0),
	"STAT_OWNRCHNDCNT" NUMBER(10,0),
	"STAT_SRTDAT" DATE,
	"STAT_CMPDAT" DATE,
	"STAT_CANCAT" DATE,
	"STAT_ID" NUMBER(19,0),
	"CCTR_AFFN_UM_EVNTREQT" NUMBER(19,0),
	"CCTR_AFFN_UM_EXTN" NUMBER(19,0),
	"CCTR_AFFN_PVDR" NUMBER(19,0),
	"CCTR_AFFN_CM" NUMBER(19,0),
	"CCTR_AFFN_MEMB" NUMBER(19,0),
	"CCTR_AFFN_UM_EVNT" NUMBER(19,0),
	"STAT_RFNGWKFWTSK" NUMBER(19,0),
	"STAT_PRVSRFNGTSK" NUMBER(19,0),
	"STAT_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"STAT_OWNR" NUMBER(19,0),
	"STAT_PRVSOWNR" NUMBER(19,0),
	"STAT_PRVSSNDR" NUMBER(19,0),
	"STAT_PRVSOWNRPRMN" NUMBER(19,0),
	"STAT_TNFR" NUMBER(19,0),
	"STAT_PRVSTNFR" NUMBER(19,0),
	"TACB_CURRQTN" NUMBER(19,0),
	"TACB_ASMTCC" NUMBER(19,0),
	"STAT_RTKNORIG" NUMBER(19,0),
	"STAT_SENTLTR" NUMBER(19,0),
	"STAT_SENTTSK" NUMBER(19,0),
	"TACB_CLLDSTTS" NUMBER(19,0),
	"TACB_MEMB" NUMBER(19,0),
	"RENDERED_ASMT" BLOB DEFAULT empty_blob()
   ) ;


  CREATE INDEX "THH_C4C"."IX_CBDG_MDCLCLM" ON "THH_C4C"."T_MEMBDGISBASE" ("CBDG_MDCLCLM")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTR_AFFN_CM" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_AFFN_CM")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTR_AFFN_MEMB" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_AFFN_MEMB")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTR_AFFN_PVDR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_AFFN_PVDR")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTR_AFFN_UM_EVNT" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_AFFN_UM_EVNT")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTR_AFFN_UM_EVNTREQT" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_AFFN_UM_EVNTREQT")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTR_AFFN_UM_EXTN" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_AFFN_UM_EXTN")
  ;


  CREATE INDEX "THH_C4C"."IX_CFDS_AMTN" ON "THH_C4C"."T_MEMBDGISBASE" ("CFDS_AMTN")
  ;


  CREATE INDEX "THH_C4C"."IX_CFDS_CM_TMPT" ON "THH_C4C"."T_MEMBDGISBASE" ("CFDS_CM_TMPT")
  ;


  CREATE INDEX "THH_C4C"."IX_CFDS_SENTASMT" ON "THH_C4C"."T_MEMBDGISBASE" ("CFDS_SENTASMT")
  ;


  CREATE INDEX "THH_C4C"."IX_CFDS_THE_BRNCACT" ON "THH_C4C"."T_MEMBDGISBASE" ("CFDS_THE_BRNCACT")
  ;


  CREATE INDEX "THH_C4C"."IX_CMDI_CMBASE_DGIS" ON "THH_C4C"."T_MEMBDGISBASE" ("CMDI_CM_BASE", "MBDB_DGIS")
  ;


  CREATE INDEX "THH_C4C"."IX_FMCT_CLASSTYPE" ON "THH_C4C"."T_FRM_CELLTXT" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_FMCT_CRTD" ON "THH_C4C"."T_FRM_CELLTXT" ("FMCT_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_FMCT_OBJ_STT" ON "THH_C4C"."T_FRM_CELLTXT" ("FMCT_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_FMCT_RSPE" ON "THH_C4C"."T_FRM_CELLTXT" ("FMCT_RSPE")
  ;


  CREATE INDEX "THH_C4C"."IX_FMCT_UNIVID" ON "THH_C4C"."T_FRM_CELLTXT" ("FMCT_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_CLASSTYPE" ON "THH_C4C"."T_MEMBDGISBASE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_CRTD" ON "THH_C4C"."T_MEMBDGISBASE" ("MBDB_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_CSTMFLDS" ON "THH_C4C"."T_MEMBDGISBASE" ("MBDB_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_DGIS" ON "THH_C4C"."T_MEMBDGISBASE" ("MBDB_DGIS")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_DGISUMEVNT_ID" ON "THH_C4C"."T_MEMBDGISBASE" ("UMDS_DGISUM_EVNT", "MBDB_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_OBJ_STT" ON "THH_C4C"."T_MEMBDGISBASE" ("MBDB_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_MBDB_UNIVID" ON "THH_C4C"."T_MEMBDGISBASE" ("MBDB_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_CAUDBY" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_CAUDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_GRP" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_GRP")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_MEMB_DGIS" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_MEMB", "MBDB_DGIS")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_OWNR" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_PRVSOWNR" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_PRVSOWNRPRMN" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_PRVSRFNGTSK" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_PRVSRFNGTSK_PRMN" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_PRVSSNDR" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_PRVSTNFR" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_RFNGWKFWTSK" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_SRC__ASMTCARECALC" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_SRC__ASMTCARECALC")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_SRC__PAT_ID_QRY" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_SRC__PAT_ID_QRY")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_TAKNASMTCC" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_TAKNASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_MDSS_TNFR" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_TNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_OBJ_STT_AFFN_MEMB_SETK_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_OBJ_STT", "SETK_AFFN_MEMB", "SETK_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_ALM_FRMA" ON "THH_C4C"."T_QTN" ("QTN_ALM_FRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_ASMTCC" ON "THH_C4C"."T_QTN" ("QTN_ASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_C4C_ID" ON "THH_C4C"."T_QTN" ("QTN_C4C_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_C4C_ID_DS" ON "THH_C4C"."T_QTN" (UPPER("QTN_C4C_ID"))
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_C4C_ID_RS" ON "THH_C4C"."T_QTN" (UPPER("THH_C4C"."REVERSE_STR"("QTN_C4C_ID")))
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_CAREBEANFRMA" ON "THH_C4C"."T_QTN" ("QTN_CAREBEANFRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_CLASSTYPE" ON "THH_C4C"."T_QTN" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_CRTD" ON "THH_C4C"."T_QTN" ("QTN_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_DGESFRMA" ON "THH_C4C"."T_QTN" ("QTN_DGESFRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_OBJ_STT" ON "THH_C4C"."T_QTN" ("QTN_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_ORIG" ON "THH_C4C"."T_QTN" ("QTN_ORIG")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_QTN_FRMA" ON "THH_C4C"."T_QTN" ("QTN_QTN_FRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_QTN_TXT" ON "THH_C4C"."T_QTN" ("QTN_QTN_TXT")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_QTN_TXT_DS" ON "THH_C4C"."T_QTN" (UPPER("QTN_QTN_TXT"))
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_QTN_TXT_RS" ON "THH_C4C"."T_QTN" (UPPER("THH_C4C"."REVERSE_STR"("QTN_QTN_TXT")))
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_REP_FRMA" ON "THH_C4C"."T_QTN" ("QTN_REP_FRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_SCLB" ON "THH_C4C"."T_QTN" ("QTN_SCLB")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_SKIPFRMA" ON "THH_C4C"."T_QTN" ("QTN_SKIPFRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_STTSFMLS" ON "THH_C4C"."T_QTN" ("QTN_STTSFMLS")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_TSK_FRMA" ON "THH_C4C"."T_QTN" ("QTN_TSK_FRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_TYP_SBTY" ON "THH_C4C"."T_QTN" ("QTN_TYP_SBTY")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_UNIVID" ON "THH_C4C"."T_QTN" ("QTN_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_VSBT" ON "THH_C4C"."T_QTN" ("QTN_VSBT")
  ;


  CREATE INDEX "THH_C4C"."IX_QTN_WGHTFRMA" ON "THH_C4C"."T_QTN" ("QTN_WGHTFRMA")
  ;


  CREATE INDEX "THH_C4C"."IX_RESP_CLASSTYPE" ON "THH_C4C"."T_RSPE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_RESP_CRTD" ON "THH_C4C"."T_RSPE" ("RESP_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_RESP_OBJ_STT" ON "THH_C4C"."T_RSPE" ("RESP_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_RESP_TAKNASMTCC" ON "THH_C4C"."T_RSPE" ("RESP_TAKNASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_RESP_UNIVID" ON "THH_C4C"."T_RSPE" ("RESP_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_RPCH_CHCS" ON "THH_C4C"."T_RSPECHCS" ("RPCH_CHCS")
  ;


  CREATE INDEX "THH_C4C"."IX_RPCH_CLASSTYPE" ON "THH_C4C"."T_RSPECHCS" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_RPCH_CRTD" ON "THH_C4C"."T_RSPECHCS" ("RPCH_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_RPCH_OBJ_STT" ON "THH_C4C"."T_RSPECHCS" ("RPCH_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_RPCH_RSPE" ON "THH_C4C"."T_RSPECHCS" ("RPCH_RSPE")
  ;


  CREATE INDEX "THH_C4C"."IX_RPCH_UNIVID" ON "THH_C4C"."T_RSPECHCS" ("RPCH_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_CAUDBY" ON "THH_C4C"."T_REP" ("RPT_CAUDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_CLASSTYPE" ON "THH_C4C"."T_REP" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_CRTD" ON "THH_C4C"."T_REP" ("RPT_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_OBJ_STT" ON "THH_C4C"."T_REP" ("RPT_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_TAKNASMTCC" ON "THH_C4C"."T_REP" ("RPT_TAKNASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_THE_BRNCACT" ON "THH_C4C"."T_REP" ("RPT_THE_BRNCACT")
  ;


  CREATE INDEX "THH_C4C"."IX_RPT_UNIVID" ON "THH_C4C"."T_REP" ("RPT_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_SCBT_CAREBEANTSK" ON "THH_C4C"."T_SENTTSK" ("SCBT_CAREBEANTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_SCBT_CB_SETK_TMTD_AFFM_OWNR" ON "THH_C4C"."T_SENTTSK" ("SCBT_CAREBEAN", "SETK_TMTD", "SETK_AFFN_MEMB", "SETK_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_SCBT_CB_STK_TD_AFM_NVL_PRNL" ON "THH_C4C"."T_SENTTSK" ("SCBT_CAREBEAN", "SETK_TMTD", "SETK_AFFN_MEMB", NVL("SETK_PRNL",0))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_AFFN_CM" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_CM")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_AFFN_MEMB" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_MEMB")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_AFFN_PVDR" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_PVDR")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_AFFN_UM_EVNT" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_UM_EVNT")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_AFFN_UM_EVNTREQT" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_UM_EVNTREQT")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_AFFN_UM_EXTN" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_UM_EXTN")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_CAUDBY" ON "THH_C4C"."T_SENTTSK" ("SETK_CAUDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_CLASSTYPE" ON "THH_C4C"."T_SENTTSK" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_CNCLRESN" ON "THH_C4C"."T_SENTTSK" ("SETK_CNCLRESN")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_CRTD" ON "THH_C4C"."T_SENTTSK" ("SETK_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_CSTMFLDS" ON "THH_C4C"."T_SENTTSK" ("SETK_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_GRP" ON "THH_C4C"."T_SENTTSK" ("SETK_GRP")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_OBJ_STT" ON "THH_C4C"."T_SENTTSK" ("SETK_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_ORIGRCPT" ON "THH_C4C"."T_SENTTSK" ("SETK_ORIGRCPT")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_OWNR" ON "THH_C4C"."T_SENTTSK" ("SETK_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_OWNRORIGRCPT" ON "THH_C4C"."T_SENTTSK" (NVL("SETK_OWNR","SETK_ORIGRCPT"))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_PRVSOWNR" ON "THH_C4C"."T_SENTTSK" ("SETK_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_PRVSOWNRPRMN" ON "THH_C4C"."T_SENTTSK" ("SETK_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_PRVSRFNGTSK" ON "THH_C4C"."T_SENTTSK" ("SETK_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_PRVSRFNGTSK_PRMN" ON "THH_C4C"."T_SENTTSK" ("SETK_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_PRVSSNDR" ON "THH_C4C"."T_SENTTSK" ("SETK_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_PRVSTNFR" ON "THH_C4C"."T_SENTTSK" ("SETK_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_REPP_STARTDATEALL" ON "THH_C4C"."T_SENTTSK" ("SETK_RETNPTRN", TRUNC(NVL("SETK_TSK_TIMG_STRTDT","SETK_TSK_TIMG_SNLTDT"))+NVL("SETK_TSK_TIMG_SCLDAT"/86400,0))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_RETNPTRN_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_RETNPTRN", "SETK_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_RFNGWKFWTSK" ON "THH_C4C"."T_SENTTSK" ("SETK_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_SENT_Y2D" ON "THH_C4C"."T_SENTTSK" (TRUNC("SETK_SENT"))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_SRC__ASMTCARECALC" ON "THH_C4C"."T_SENTTSK" ("SETK_SRC__ASMTCARECALC")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_SRC__PAT_ID_QRY" ON "THH_C4C"."T_SENTTSK" ("SETK_SRC__PAT_ID_QRY")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_STARTDATEALL" ON "THH_C4C"."T_SENTTSK" (TRUNC(NVL("SETK_TSK_TIMG_STRTDT","SETK_TSK_TIMG_SNLTDT"))+NVL("SETK_TSK_TIMG_SCLDAT"/86400,0))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_STRTSNLTDT_LOWB" ON "THH_C4C"."T_SENTTSK" ("THH_C4C"."GET_RANGE_LOWBOUND_VALUE"(NVL("SETK_TSK_TIMG_STRTDT","SETK_TSK_TIMG_SNLTDT"),"SETK_TMTD"))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_TAKNASMTCC_BASE" ON "THH_C4C"."T_SENTTSK" ("SETK_TAKNASMTCC_BASE")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_TMPT" ON "THH_C4C"."T_SENTTSK" ("SETK_TMPT")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_TMTD_HIGHB" ON "THH_C4C"."T_SENTTSK" ("THH_C4C"."GET_RANGE_HIGHBOUND_VALUE"(NVL("SETK_TSK_TIMG_STRTDT","SETK_TSK_TIMG_SNLTDT"),"SETK_TMTD"))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_TMTD_HIGHBX" ON "THH_C4C"."T_SENTTSK" ("THH_C4C"."GET_RANGE_HIGHBOUNDX_VALUE"(NVL("SETK_TSK_TIMG_STRTDT","SETK_TSK_TIMG_SNLTDT"),"SETK_TMTD"))
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_TNFR" ON "THH_C4C"."T_SENTTSK" ("SETK_TNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_TSK_TYP" ON "THH_C4C"."T_SENTTSK" ("SETK_TSK_TYP")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_UM_BASE" ON "THH_C4C"."T_SENTTSK" ("SETK_UM_BASE")
  ;


  CREATE INDEX "THH_C4C"."IX_SETK_UNIVID" ON "THH_C4C"."T_SENTTSK" ("SETK_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_SKC4CID_SKID_SKTSKNM_CT" ON "THH_C4C"."T_SENTTSK" ("SETK_C4C_ID", "SETK_ID", "SETK_TSK_NAM", "CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_OWNR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_PRVSOWNR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_PRVSOWNRPRMN" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_PRVSRFNGTSK" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_PRVSRFNGTSK_PRMN" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_PRVSSNDR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_PRVSTNFR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_RFNGWKFWTSK" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_RTKNORIG" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_RTKNORIG")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_SENTLTR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_SENTLTR")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_SENTTSK" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_SENTTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_STAT_TNFR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_TNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_CAUDBY" ON "THH_C4C"."T_STTS" ("STA_CAUDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_CLASSTYPE" ON "THH_C4C"."T_STTS" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_CRTD" ON "THH_C4C"."T_STTS" ("STA_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_OBJ_STT" ON "THH_C4C"."T_STTS" ("STA_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_TAKNASMTCC" ON "THH_C4C"."T_STTS" ("STA_TAKNASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_THE_BRNCACT" ON "THH_C4C"."T_STTS" ("STA_THE_BRNCACT")
  ;


  CREATE INDEX "THH_C4C"."IX_STA_UNIVID" ON "THH_C4C"."T_STTS" ("STA_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_AFFN_CM" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_AFFN_CM")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_AFFN_MEMB" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_AFFN_MEMB")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_AFFN_PVDR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_AFFN_PVDR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_AFFN_UM_EVNT" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_AFFN_UM_EVNT")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_AFFN_UM_EVNTREQT" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_AFFN_UM_EVNTREQT")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_AFFN_UM_EXTN" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_AFFN_UM_EXTN")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_CAREBEAN" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_CAREBEAN")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_CAUDBY" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_CAUDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_CLASSTYPE" ON "THH_C4C"."T_SENTCAREBEAN" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_CRTD" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_CSTMFLDS" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_GRP" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_GRP")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_LAS_GKPR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_LAS_GKPR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_OBJ_STT" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_ORIGRCPT" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_ORIGRCPT")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_OWNR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_PRVSOWNR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_PRVSOWNRPRMN" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_PRVSRFNGTSK" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_PRVSRFNGTSK_PRMN" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_PRVSSNDR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_PRVSTNFR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_RFNGWKFWTSK" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_SENT_Y2D" ON "THH_C4C"."T_SENTCAREBEAN" (TRUNC("STCB_SENT"))
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_SRC__ASMTCARECALC" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_SRC__ASMTCARECALC")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_SRC__PAT_ID_QRY" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_SRC__PAT_ID_QRY")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_TAKNASMTCC" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_TAKNASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_TAKNASMTCC_BASE" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_TAKNASMTCC_BASE")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_TNFR" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_TNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_STCB_UNIVID" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_ASMTCC" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_ASMTCC")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_CLASSTYPE" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_CLLDSTTS" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_CLLDSTTS")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_CRTD" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_CURRQTN" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_CURRQTN")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_MEMB" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_MEMB")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_OBJ_STT" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_TACB_UNIVID" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_UMAD_UMBS" ON "THH_C4C"."T_MEMBDGISBASE" ("UMAD_UMBS")
  ;


  CREATE INDEX "THH_C4C"."IX_UMDS_DGISUMEVNT_DGIS" ON "THH_C4C"."T_MEMBDGISBASE" ("UMDS_DGISUM_EVNT", "MBDB_DGIS")
  ;


  CREATE INDEX "THH_C4C"."IX_UMDS_SNP" ON "THH_C4C"."T_MEMBDGISBASE" ("UMDS_SNP")
  ;


  CREATE INDEX "THH_C4C"."PERFTMEMBDGISX5" ON "THH_C4C"."T_MEMBDGISBASE" ("UMDS_DGISUM_EVNT", "CLASSTYPE", "MBDB_DGIS")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_FRM_CELLTXT" ON "THH_C4C"."T_FRM_CELLTXT" ("FMCT_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_MEMBDGISBASE" ON "THH_C4C"."T_MEMBDGISBASE" ("MBDB_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_QTN" ON "THH_C4C"."T_QTN" ("QTN_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_REP" ON "THH_C4C"."T_REP" ("RPT_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_RSPE" ON "THH_C4C"."T_RSPE" ("RESP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_RSPECHCS" ON "THH_C4C"."T_RSPECHCS" ("RPCH_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_SENTCAREBEAN" ON "THH_C4C"."T_SENTCAREBEAN" ("STCB_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_SENTTSK" ON "THH_C4C"."T_SENTTSK" ("SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_STTS" ON "THH_C4C"."T_STTS" ("STA_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_TAKNASMTCC_BASE" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("TACB_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."SYS_IL0000115282C00051$$" ON "THH_C4C"."T_TAKNASMTCC_BASE" (
  ;


  CREATE INDEX "THH_C4C"."T_CFPRBLMDS_THE_BRNCACT" ON "THH_C4C"."T_MEMBDGISBASE" ("CFPRBLMDS_THE_BRNCACT")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."T_SENTSK_UX_EVNTREQT_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_UM_EVNTREQT", "SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."T_SENTTSK_UX_CM_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_CM", "SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."T_SENTTSK_UX_EVNT_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_UM_EVNT", "SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."T_SENTTSK_UX_EXTN_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_UM_EXTN", "SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."T_SENTTSK_UX_MEMB_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_AFFN_MEMB", "SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."T_SENTTSK_UX_ORIG_ID" ON "THH_C4C"."T_SENTTSK" ("SETK_ORIGRCPT", "SETK_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CBDG" ON "THH_C4C"."T_MEMBDGISBASE" ("CBDG_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CCTR" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("CCTR_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CFDS" ON "THH_C4C"."T_MEMBDGISBASE" ("CFDS_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CFPRBLMDS" ON "THH_C4C"."T_MEMBDGISBASE" ("CFPRBLMDS_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CMDI" ON "THH_C4C"."T_MEMBDGISBASE" ("CMDI_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_MDSS" ON "THH_C4C"."T_MEMBDGISBASE" ("MDSS_ID")
  ;


  CREATE INDEX "THH_C4C"."UK_RSPE_QTN_SENTASSM" ON "THH_C4C"."T_RSPE" ("RESP_QTN", "RESP_TAKNASMTCC")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_SCBT" ON "THH_C4C"."T_SENTTSK" ("SCBT_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_STAT" ON "THH_C4C"."T_TAKNASMTCC_BASE" ("STAT_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_UMAD" ON "THH_C4C"."T_MEMBDGISBASE" ("UMAD_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_UMDS" ON "THH_C4C"."T_MEMBDGISBASE" ("UMDS_ID")
  ;

