
  CREATE TABLE "THH_C4C"."A_APBL"
   (	"APBL_LAS_ACT" NUMBER(10,0),
	"APBL_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"APBL_OBJ_STT" NUMBER(10,0),
	"APBL_VERS" NUMBER(19,0),
	"APBL_VSBT" NUMBER(10,0),
	"APBL_DLTDDT" DATE,
	"APBL_LAS_ACT_BY" NUMBER(19,0),
	"APBL_ORIGCRTR" NUMBER(19,0),
	"APBL_ORIGCRTRLOGDIN" NUMBER(19,0),
	"APBL_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"APBL_UNIVID" VARCHAR2(4000),
	"APBL_RQTDDT_FROM" DATE,
	"APBL_RQTDDT_TO" DATE,
	"APBL_RQTDQNTY" NUMBER(10,0),
	"APBL_APRDDT_FROM" DATE,
	"APBL_APRDDT_TO" DATE,
	"APBL_APRDQNTY" NUMBER(10,0),
	"APBL_ACTLDT_FROM" DATE,
	"APBL_ACTLDT_TO" DATE,
	"APBL_ACTLQNTY" NUMBER(10,0),
	"APBL_AUTHID" VARCHAR2(4000),
	"APBL_SEQ" NUMBER(19,0),
	"APBL_CMMT" VARCHAR2(4000),
	"APBL_DTMN" NUMBER(10,0),
	"APBL_IS_ERR" NUMBER(1,0),
	"APBL_ERR_TXT" VARCHAR2(4000),
	"UMXT_WKFWISTCID" VARCHAR2(4000),
	"UMXT_CNV_ID" VARCHAR2(4000),
	"UMXT_OWNRCHNDFLAG" NUMBER(1,0),
	"UMXT_OWNRCHNDCNT" NUMBER(10,0),
	"UMXT_MNLYDRMDAT" DATE,
	"UMXT_ID" NUMBER(19,0),
	"MSRV_CUMEAPRDDT_FROM" DATE,
	"MSRV_CUMEAPRDQNTY" NUMBER(10,0),
	"MSRV_CUMEAPRDDT_TO" DATE,
	"MSRV_WKFWISTCID" VARCHAR2(4000),
	"MSRV_CNV_ID" VARCHAR2(4000),
	"MSRV_OWNRCHNDFLAG" NUMBER(1,0),
	"MSRV_OWNRCHNDCNT" NUMBER(10,0),
	"MSRV_MNLYDRMDAT" DATE,
	"MSRV_ID" NUMBER(19,0),
	"UMXT_RFNGWKFWTSK" NUMBER(19,0),
	"UMXT_PRVSRFNGTSK" NUMBER(19,0),
	"UMXT_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"UMXT_OWNR" NUMBER(19,0),
	"UMXT_PRVSOWNR" NUMBER(19,0),
	"UMXT_PRVSSNDR" NUMBER(19,0),
	"UMXT_PRVSOWNRPRMN" NUMBER(19,0),
	"UMXT_TNFR" NUMBER(19,0),
	"UMXT_PRVSTNFR" NUMBER(19,0),
	"UMXT_MNLYDRMDBY" NUMBER(19,0),
	"MSRV_RFNGWKFWTSK" NUMBER(19,0),
	"MSRV_PRVSRFNGTSK" NUMBER(19,0),
	"MSRV_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"MSRV_OWNR" NUMBER(19,0),
	"MSRV_PRVSOWNR" NUMBER(19,0),
	"MSRV_PRVSSNDR" NUMBER(19,0),
	"MSRV_PRVSOWNRPRMN" NUMBER(19,0),
	"MSRV_TNFR" NUMBER(19,0),
	"MSRV_PRVSTNFR" NUMBER(19,0),
	"MSRV_MNLYDRMDBY" NUMBER(19,0),
	"MSRV_CSTMFLDS" NUMBER(19,0),
	"MSRV_MDCLSRVCTYP" NUMBER(19,0),
	"MSRV_PLCEOF_SRVCTYP" NUMBER(19,0),
	"MSRV_BED_TYP" NUMBER(19,0),
	"UMXT_PRNTEVNT" NUMBER(19,0),
	"APBL_DENLRESN" NUMBER(19,0),
	"UMXT_DCLYXTDD" NUMBER(19,0),
	"APBL_ACTLUNTS" NUMBER(19,0),
	"APBL_APRDUNTS" NUMBER(19,0),
	"APBL_RQTDUNTS" NUMBER(19,0),
	"UMXT_XTDD" NUMBER(19,0),
	"MSRV_SRVCDGIS" NUMBER(19,0),
	"MSRV_LAS_EXTN" NUMBER(19,0),
	"MSRV_PVDRASTN" NUMBER(19,0),
	"MSRV_SNP" NUMBER(19,0),
	"CLASSTYPE" VARCHAR2(255),
	"APBL_C4C_ID" VARCHAR2(4000),
	"APBL_CRTD" DATE,
	"APBL_ID" NUMBER(19,0),
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"APBL_AUDID" NUMBER,
	"APBL_PREV_AUDID" NUMBER,
	"APBL_NEXT_AUDID" NUMBER,
	"MSRV_FEES_VRFD" NUMBER(1,0) DEFAULT 0,
	"MSRV_CNTRCT_ID" VARCHAR2(30),
	"MSRV_LAST_FILL_DATE" DATE,
	"MSRV_DATE_WRITTEN" DATE,
	"MSRV_REFILLS" NUMBER(4,0),
	"MSRV_SUBSTITUTION" NUMBER(19,0),
	"TRANSACTION_ID" VARCHAR2(4000),
	"APBL_DEC_PRTY" NUMBER(19,0),
	"APBL_SRV_CDE_MOD" NUMBER(19,0),
	"APBL_REF_CAT" NUMBER(19,0),
	"APBL_REF_CAT_MOD" NUMBER(19,0),
	"APBL_DET_RSN" NUMBER(19,0),
	"UMXT_RSN" NUMBER(19,0),
	"APBL_DTMN_DUE" DATE,
	"MSRV_SRVC_AGRMNT" NUMBER(1,0) DEFAULT 0,
	"MSRV_PAY_AT_MAX" NUMBER(1,0),
	"MSRV_CVR_THR_DISCHARGE" NUMBER(1,0),
	"MSRV_IN_NETWORK" NUMBER(1,0),
	"MSRV_EXTEND_LIMIT" NUMBER(1,0),
	"MSRV_RMBRSMNT_MTHD" NUMBER(19,0),
	"MSRV_RMBRSMNT_AMOUNT" NUMBER(19,2),
	"MSRV_FLAT_FEE_TYPE" NUMBER(19,0),
	"MSRV_PCT_BILLED" NUMBER(19,2),
	"APBL_UMEVENT" NUMBER(19,0),
	"MSRV_LEVEL_OF_SERV" NUMBER(19,0),
	"MSRV_EXP_REQUESTOR" NUMBER(19,0),
	"MSRV_PROCESS_AS" NUMBER(19,0),
	"MSRV_HEALTH_PLAN_RCVD" TIMESTAMP (6),
	"MSRV_DEPT_RCVD" TIMESTAMP (6),
	"DSCE_ACTUAL_ADMIT" DATE,
	"DSCE_ACTUAL_DISCHARGE" DATE,
	"DSCE_DISPOSITION" NUMBER(19,0),
	"MSRV_SRVC_LMAN_TERMS" NUMBER(19,0),
	"DENIAL_SERVICE_CATEGORY" NUMBER(19,0),
	"DENIAL_SERVICE_REASON" NUMBER(19,0),
	"ACTION_TYPE" NUMBER(19,0),
	"APBL_DENIED_QTY" NUMBER(10,0),
	"APBL_DENIED_DATE_FROM" DATE,
	"APBL_DENIED_DATE_TO" DATE,
	"APBL_DENIED_UNITS" NUMBER(19,0),
	"CLINICALDATAENTRY_ID" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."A_CM_BASEBASE"
   (	"CSRQ_RJTNRESN" NUMBER(19,0),
	"CASE_CLSRRESN" NUMBER(19,0),
	"CASE_PRJ_OTCM" NUMBER(19,0),
	"CASE_LAS_CLSDBY" NUMBER(19,0),
	"CASE_LAS_RPNDBY" NUMBER(19,0),
	"CASE_RFNGWKFWTSK" NUMBER(19,0),
	"CASE_PRVSRFNGTSK" NUMBER(19,0),
	"CASE_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"CASE_OWNR" NUMBER(19,0),
	"CASE_PRVSOWNR" NUMBER(19,0),
	"CASE_PRVSSNDR" NUMBER(19,0),
	"CASE_PRVSOWNRPRMN" NUMBER(19,0),
	"CASE_TNFR" NUMBER(19,0),
	"CASE_PRVSTNFR" NUMBER(19,0),
	"CASE_RCPTTRKG" NUMBER(19,0),
	"CASE_LAS_REVW" NUMBER(19,0),
	"CASE_FRSTOPNDBY" NUMBER(19,0),
	"CASE_REONRESN" NUMBER(19,0),
	"CMPQ_DENLRESN" NUMBER(19,0),
	"CMPQ_LAS_SBTDBY" NUMBER(19,0),
	"CMPQ_FRSTSBTDBY" NUMBER(19,0),
	"CMPQ_RFNGWKFWTSK" NUMBER(19,0),
	"CMPQ_PRVSRFNGTSK" NUMBER(19,0),
	"CMPQ_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"CMPQ_OWNR" NUMBER(19,0),
	"CMPQ_PRVSOWNR" NUMBER(19,0),
	"CMPQ_PRVSSNDR" NUMBER(19,0),
	"CMPQ_PRVSOWNRPRMN" NUMBER(19,0),
	"CMPQ_TNFR" NUMBER(19,0),
	"CMPQ_PRVSTNFR" NUMBER(19,0),
	"CMPQ_RCPTTRKG" NUMBER(19,0),
	"CMPQ_LAS_REVW" NUMBER(19,0),
	"CMPQ_LAS_RTEDTO" NUMBER(19,0),
	"CMPQ_RTNGRCPT" NUMBER(19,0),
	"CMPQ_RJTNRESN" NUMBER(19,0),
	"CMPR_CLSRRESN" NUMBER(19,0),
	"CMPR_PRJ_OTCM" NUMBER(19,0),
	"CMPR_LAS_CLSDBY" NUMBER(19,0),
	"CMPR_LAS_RPNDBY" NUMBER(19,0),
	"CMPR_RFNGWKFWTSK" NUMBER(19,0),
	"CMPR_PRVSRFNGTSK" NUMBER(19,0),
	"CMPR_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"CMPR_OWNR" NUMBER(19,0),
	"CMPR_PRVSOWNR" NUMBER(19,0),
	"CMPR_PRVSSNDR" NUMBER(19,0),
	"CMPR_PRVSOWNRPRMN" NUMBER(19,0),
	"CMPR_TNFR" NUMBER(19,0),
	"CMPR_PRVSTNFR" NUMBER(19,0),
	"CMPR_RCPTTRKG" NUMBER(19,0),
	"CMPR_LAS_REVW" NUMBER(19,0),
	"CMPR_FRSTOPNDBY" NUMBER(19,0),
	"CMPR_REONRESN" NUMBER(19,0),
	"CMBB_SRC" NUMBER(19,0),
	"CMBB_TYP" NUMBER(19,0),
	"CMBB_RESN" NUMBER(19,0),
	"CMBB_PITY" NUMBER(19,0),
	"CMBB_SVTY" NUMBER(19,0),
	"CMBB_OWNROBST" NUMBER(19,0),
	"CMBB_PMRYPVDR" NUMBER(19,0),
	"CMBB_RTNGRCPT" NUMBER(19,0),
	"CMBB_CSTMFLDS" NUMBER(19,0),
	"CMBS_MEMB" NUMBER(19,0),
	"CMBS_TMPT" NUMBER(19,0),
	"CMBS_PAT_ID_QRY" NUMBER(19,0),
	"CMBS_QRY_STTS" NUMBER(19,0),
	"CSRQ_RTNGPEER" NUMBER(19,0),
	"CASE_REQT" NUMBER(19,0),
	"CMPQ_RTNGPEER" NUMBER(19,0),
	"CMPR_REQT" NUMBER(19,0),
	"CMTB_AMTN" NUMBER(19,0),
	"CLASSTYPE" VARCHAR2(255),
	"CMBB_C4C_ID" VARCHAR2(4000),
	"CMBB_CRTD" DATE,
	"CMBB_LAS_ACT" NUMBER(10,0),
	"CMBB_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"CMBB_OBJ_STT" NUMBER(10,0),
	"CMBB_VERS" NUMBER(19,0),
	"CMBB_VSBT" NUMBER(10,0),
	"CMBB_DLTDDT" DATE,
	"CMBB_LAS_ACT_BY" NUMBER(19,0),
	"CMBB_ORIGCRTR" NUMBER(19,0),
	"CMBB_ORIGCRTRLOGDIN" NUMBER(19,0),
	"CMBB_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"CMBB_UNIVID" VARCHAR2(4000),
	"CMBB_RTNGSTNG" NUMBER(10,0),
	"CMBS_INI_CNCTDT_TIM__DT" DATE,
	"CMBS_INI_CNCTDT_TIM__TIM_IN_DY" NUMBER(10,0),
	"CMBS_DENLCMMT" VARCHAR2(4000),
	"CMBS_ID" NUMBER(19,0),
	"CBS_ID" NUMBER(19,0),
	"CSRQ_RJTNCMMT" VARCHAR2(4000),
	"CSRQ_FRSTSBTDAT" DATE,
	"CSRQ_LAS_SBTDAT" DATE,
	"CSRQ_WKFWISTCID" VARCHAR2(4000),
	"CSRQ_CNV_ID" VARCHAR2(4000),
	"CSRQ_OWNRCHNDFLAG" NUMBER(1,0),
	"CSRQ_OWNRCHNDCNT" NUMBER(10,0),
	"CSRQ_LAS_RTEDAT" DATE,
	"CSRQ_DDLNTYP" NUMBER(10,0),
	"CSRQ_DDLNDT__DT" DATE,
	"CSRQ_DDLNDT__TIM_IN_DY" NUMBER(10,0),
	"CSRQ_DDLNTIM_BLCK" NUMBER(10,0),
	"CSRQ_DDLNTIM_BLCKUNITTYP" NUMBER(10,0),
	"CSRQ_IS_OK_AFT_DDLN" NUMBER(1,0),
	"CSRQ_ID" NUMBER(19,0),
	"CASE_CLNGCMMT" VARCHAR2(4000),
	"CASE_REONCMMT" VARCHAR2(4000),
	"CASE_ACKGDDLN_DT" DATE,
	"CASE_ACKGDDLN_TIM_IN_DY" NUMBER(10,0),
	"CASE_LAS_CLSD" DATE,
	"CASE_LAS_RPND" DATE,
	"CASE_WKFWISTCID" VARCHAR2(4000),
	"CASE_CNV_ID" VARCHAR2(4000),
	"CASE_OWNRCHNDFLAG" NUMBER(1,0),
	"CASE_OWNRCHNDCNT" NUMBER(10,0),
	"CASE_FRSTOPND" DATE,
	"CASE_ID" NUMBER(19,0),
	"CMPB_ID" NUMBER(19,0),
	"CMPQ_RJTNCMMT" VARCHAR2(4000),
	"CMPQ_FRSTSBTDAT" DATE,
	"CMPQ_LAS_SBTDAT" DATE,
	"CMPQ_WKFWISTCID" VARCHAR2(4000),
	"CMPQ_CNV_ID" VARCHAR2(4000),
	"CMPQ_OWNRCHNDFLAG" NUMBER(1,0),
	"CMPQ_OWNRCHNDCNT" NUMBER(10,0),
	"CMPQ_LAS_RTEDAT" DATE,
	"CMPQ_DDLNTYP" NUMBER(10,0),
	"CMPQ_DDLNDT__DT" DATE,
	"CMPQ_DDLNDT__TIM_IN_DY" NUMBER(10,0),
	"CMPQ_DDLNTIM_BLCK" NUMBER(10,0),
	"CMPQ_DDLNTIM_BLCKUNITTYP" NUMBER(10,0),
	"CMPQ_IS_OK_AFT_DDLN" NUMBER(1,0),
	"CMPQ_ID" NUMBER(19,0),
	"CMPR_CLNGCMMT" VARCHAR2(4000),
	"CMPR_REONCMMT" VARCHAR2(4000),
	"CMPR_ACKGDDLN_DT" DATE,
	"CMPR_ACKGDDLN_TIM_IN_DY" NUMBER(10,0),
	"CMPR_LAS_CLSD" DATE,
	"CMPR_LAS_RPND" DATE,
	"CMPR_WKFWISTCID" VARCHAR2(4000),
	"CMPR_CNV_ID" VARCHAR2(4000),
	"CMPR_OWNRCHNDFLAG" NUMBER(1,0),
	"CMPR_OWNRCHNDCNT" NUMBER(10,0),
	"CMPR_FRSTOPND" DATE,
	"CMPR_ID" NUMBER(19,0),
	"CMTB_TMPTTYP" NUMBER(10,0),
	"CMTB_ID" NUMBER(19,0),
	"CRQB_DDLNTYP" NUMBER(10,0),
	"CRQB_DDLNDT__DT" DATE,
	"CRQB_DDLNDT__TIM_IN_DY" NUMBER(10,0),
	"CRQB_DDLNTIM_BLCK" NUMBER(10,0),
	"CRQB_DDLNTIM_BLCKUNITTYP" NUMBER(10,0),
	"CRQB_IS_OK_AFT_DDLN" NUMBER(1,0),
	"CRQB_ID" NUMBER(19,0),
	"CRTB_ID" NUMBER(19,0),
	"CSRQ_DENLRESN" NUMBER(19,0),
	"CSRQ_LAS_SBTDBY" NUMBER(19,0),
	"CSRQ_FRSTSBTDBY" NUMBER(19,0),
	"CSRQ_RFNGWKFWTSK" NUMBER(19,0),
	"CSRQ_PRVSRFNGTSK" NUMBER(19,0),
	"CSRQ_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"CSRQ_OWNR" NUMBER(19,0),
	"CSRQ_PRVSOWNR" NUMBER(19,0),
	"CSRQ_PRVSSNDR" NUMBER(19,0),
	"CSRQ_PRVSOWNRPRMN" NUMBER(19,0),
	"CSRQ_TNFR" NUMBER(19,0),
	"CSRQ_PRVSTNFR" NUMBER(19,0),
	"CSRQ_RCPTTRKG" NUMBER(19,0),
	"CSRQ_LAS_REVW" NUMBER(19,0),
	"CSRQ_LAS_RTEDTO" NUMBER(19,0),
	"CSRQ_RTNGRCPT" NUMBER(19,0),
	"CMBB_ID" NUMBER(19,0),
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"CMBB_AUDID" NUMBER,
	"CMBB_PREV_AUDID" NUMBER,
	"CMBB_NEXT_AUDID" NUMBER,
	"NEXT_REVIEW_DATE" DATE,
	"PARTICIPATION" NUMBER(19,0),
	"REQUESTOR" NUMBER(19,0),
	"STAGE" NUMBER(19,0),
	"TGT_INTERVENTION" NUMBER(19,0),
	"PARTICIPATIONSTATUS" NUMBER(19,0),
	"DUEDATE" DATE,
	"TIMING" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."A_MEMBDGISBASE"
   (	"CLASSTYPE" VARCHAR2(255),
	"MBDB_C4C_ID" VARCHAR2(4000),
	"MBDB_CRTD" DATE,
	"MBDB_LAS_ACT" NUMBER(10,0),
	"MBDB_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"MBDB_OBJ_STT" NUMBER(10,0),
	"MBDB_VERS" NUMBER(19,0),
	"MBDB_VSBT" NUMBER(10,0),
	"MBDB_DLTDDT" DATE,
	"MBDB_LAS_ACT_BY" NUMBER(19,0),
	"MBDB_ORIGCRTR" NUMBER(19,0),
	"MBDB_ORIGCRTRLOGDIN" NUMBER(19,0),
	"MBDB_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"MBDB_UNIVID" VARCHAR2(4000),
	"MBDB_RESNOR_CMMT" VARCHAR2(4000),
	"CFDS_ID" NUMBER(19,0),
	"MDSS_STRTDT" DATE,
	"MDSS_END_DT" DATE,
	"MDSS_RSLVDT" DATE,
	"MDSS_RSTNCMMT" VARCHAR2(4000),
	"MDSS_IS_PMRYDGIS" NUMBER(1,0),
	"MDSS_IS_REQ_AND_PERFPROVSAME" NUMBER(1,0),
	"MDSS_IS_SLTD" NUMBER(1,0),
	"MDSS_IS_ERR" NUMBER(1,0),
	"MDSS_SRC_USR_NAM" VARCHAR2(4000),
	"MDSS_ERR_TXT" VARCHAR2(4000),
	"MDSS_WKFWISTCID" VARCHAR2(4000),
	"MDSS_CNV_ID" VARCHAR2(4000),
	"MDSS_OWNRCHNDFLAG" NUMBER(1,0),
	"MDSS_OWNRCHNDCNT" NUMBER(10,0),
	"MDSS_SRC__SRC_TYP" NUMBER(10,0),
	"MDSS_ID" NUMBER(19,0),
	"CBDG_ID" NUMBER(19,0),
	"UMAD_ID" NUMBER(19,0),
	"CMDI_ID" NUMBER(19,0),
	"UMDS_ID" NUMBER(19,0),
	"MDSS_RFNGWKFWTSK" NUMBER(19,0),
	"MDSS_PRVSRFNGTSK" NUMBER(19,0),
	"MDSS_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"MDSS_OWNR" NUMBER(19,0),
	"MDSS_PRVSOWNR" NUMBER(19,0),
	"MDSS_PRVSSNDR" NUMBER(19,0),
	"MDSS_PRVSOWNRPRMN" NUMBER(19,0),
	"MDSS_TNFR" NUMBER(19,0),
	"MDSS_PRVSTNFR" NUMBER(19,0),
	"MDSS_SRC__ASMTCARECALC" NUMBER(19,0),
	"MDSS_SRC__PAT_ID_QRY" NUMBER(19,0),
	"CMDI_CM_BASE" NUMBER(19,0),
	"CFDS_CM_TMPT" NUMBER(19,0),
	"CFDS_THE_BRNCACT" NUMBER(19,0),
	"MBDB_DGIS" NUMBER(19,0),
	"CFDS_SENTASMT" NUMBER(19,0),
	"MDSS_CAUDBY" NUMBER(19,0),
	"MDSS_TAKNASMTCC" NUMBER(19,0),
	"MDSS_MEMB" NUMBER(19,0),
	"CBDG_MDCLCLM" NUMBER(19,0),
	"UMAD_UMBS" NUMBER(19,0),
	"CFDS_AMTN" NUMBER(19,0),
	"MBDB_CSTMFLDS" NUMBER(19,0),
	"UMDS_DGISUM_EVNT" NUMBER(19,0),
	"UMDS_SNP" NUMBER(19,0),
	"MDSS_GRP" NUMBER(19,0),
	"MBDB_ID" NUMBER(19,0),
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"MBDB_AUDID" NUMBER,
	"MBDB_PREV_AUDID" NUMBER,
	"MBDB_NEXT_AUDID" NUMBER,
	"MPDS_PRBLM_DSCRP" VARCHAR2(4000),
	"MPDS_PRBLM_NAME" VARCHAR2(4000),
	"MPDS_PRBLM_CLSRRSN" NUMBER(19,0),
	"MPDS_PRBLM_STATUS" NUMBER(19,0),
	"MPDS_PRBLM_SRC" NUMBER(19,0),
	"MPDS_PRBLM_SRC_ID" NUMBER(19,0),
	"MPDS_PRBLM_COMMENT" VARCHAR2(4000),
	"MPDS_PRBLM_GNRTD_FRM_SRC_ID" NUMBER(19,0),
	"CFPRBLMDS_THE_BRNCACT" NUMBER(19,0),
	"CFPRBLMDS_ID" NUMBER(19,0),
	"CFPRBLMDS_SENTASMT" NUMBER(19,0),
	"PRBLM_CAUDBY" NUMBER(19,0),
	"PRBLM_TAKNASMTCC" NUMBER(19,0),
	"TRANSACTION_ID" VARCHAR2(4000)
   ) ;


  CREATE TABLE "THH_C4C"."A_PVDRASTN"
   (	"CLASSTYPE" VARCHAR2(255),
	"PRAS_C4C_ID" VARCHAR2(4000),
	"PRAS_CRTD" DATE,
	"PRAS_LAS_ACT" NUMBER(10,0),
	"PRAS_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"PRAS_OBJ_STT" NUMBER(10,0),
	"PRAS_VERS" NUMBER(19,0),
	"PRAS_VSBT" NUMBER(10,0),
	"PRAS_DLTDDT" DATE,
	"PRAS_LAS_ACT_BY" NUMBER(19,0),
	"PRAS_ORIGCRTR" NUMBER(19,0),
	"PRAS_ORIGCRTRLOGDIN" NUMBER(19,0),
	"PRAS_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"PRAS_UNIVID" VARCHAR2(4000),
	"PRAS_STRTDT" DATE,
	"PRAS_END_DT" DATE,
	"PRAS_CMMT" VARCHAR2(4000),
	"PRAS_SRC_NAM_ID" NUMBER(10,0),
	"CPAS_PMRYPVDR" NUMBER(1,0),
	"CPAS_ID" NUMBER(19,0),
	"MSPA_ID" NUMBER(19,0),
	"MPAS_ID" NUMBER(19,0),
	"UPAS_PMRYPVDR" NUMBER(1,0),
	"UPAS_RQNGPVDR" NUMBER(1,0),
	"UPAS_PFNGPVDR" NUMBER(1,0),
	"UPAS_ID" NUMBER(19,0),
	"CPAS_CM_BASE" NUMBER(19,0),
	"PRAS_ROLE" NUMBER(19,0),
	"UPAS_PVDRUM_BASE" NUMBER(19,0),
	"PRAS_PVDR" NUMBER(19,0),
	"MPAS_MEMB" NUMBER(19,0),
	"MPAS_DRUGCLM" NUMBER(19,0),
	"MPAS_MDCLCLM" NUMBER(19,0),
	"PRAS_ID" NUMBER(19,0),
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"PRAS_AUDID" NUMBER,
	"PRAS_PREV_AUDID" NUMBER,
	"PRAS_NEXT_AUDID" NUMBER,
	"PRAS_DISTANCE_MEMBER" NUMBER(10,0),
	"PRAS_NETWORK_STATUS" NUMBER(1,0),
	"PRAS_ADDRESS_STRING" VARCHAR2(4000),
	"PRAS_AUDIT_KEY" NUMBER(19,0),
	"PRAS_PRACTITIONER_LOCATION" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."A_UM_BASE"
   (	"CLASSTYPE" VARCHAR2(255),
	"UMBS_C4C_ID" VARCHAR2(4000),
	"UMBS_CRTD" DATE,
	"UMBS_LAS_ACT" NUMBER(10,0),
	"UMBS_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"UMBS_OBJ_STT" NUMBER(10,0),
	"UMBS_VERS" NUMBER(19,0),
	"UMBS_VSBT" NUMBER(10,0),
	"UMBS_DLTDDT" DATE,
	"UMBS_LAS_ACT_BY" NUMBER(19,0),
	"UMBS_ORIGCRTR" NUMBER(19,0),
	"UMBS_ORIGCRTRLOGDIN" NUMBER(19,0),
	"UMBS_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"UMBS_UNIVID" VARCHAR2(4000),
	"UMBS_INI_CNCTDT_TIM__DT" DATE,
	"UMBS_INI_CNCTDT_TIM__TIM_IN_DY" NUMBER(10,0),
	"UMBS_RCMDLOS" NUMBER(10,0),
	"UMBS_SHOWTO_RQTR" NUMBER(1,0),
	"UMBS_RTNG" NUMBER(10,0),
	"UMBS_DDLNTYP" NUMBER(19,0),
	"UMBS_DDLNTIM_BLCKUNIT" NUMBER(19,0),
	"UMBS_DDLNTIM_BLCK" NUMBER(10,0),
	"UMBS_DDLNDT__DT" DATE,
	"UMBS_DDLNDT__TIM_IN_DY" NUMBER(10,0),
	"UMBS_CMMT" VARCHAR2(4000),
	"UMBS_REQTTYP" NUMBER(10,0),
	"UMBS_DRVDDTMNSTT" NUMBER(10,0),
	"UMET_CLNGCMTS" VARCHAR2(4000),
	"UMET_ACKGDDLN_DT" DATE,
	"UMET_ACKGDDLN_TIM_IN_DY" NUMBER(10,0),
	"UMET_CLSEDT__DT" DATE,
	"UMET_CLSEDT__TIM_IN_DY" NUMBER(10,0),
	"UMET_REONCMMT" VARCHAR2(4000),
	"UMET_LAS_CLSD" DATE,
	"UMET_LAS_RPND" DATE,
	"UMET_WKFWISTCID" VARCHAR2(4000),
	"UMET_CNV_ID" VARCHAR2(4000),
	"UMET_OWNRCHNDFLAG" NUMBER(1,0),
	"UMET_OWNRCHNDCNT" NUMBER(10,0),
	"UMET_FRSTOPNDAT" DATE,
	"UMET_ID" NUMBER(19,0),
	"UMER_IS_OK_AFT_DDLN" NUMBER(1,0),
	"UMER_DTMN" NUMBER(19,0),
	"UMER_CLSEEVNTAFT_CRTN" NUMBER(1,0),
	"UMER_RJTNCMMT" VARCHAR2(4000),
	"UMER_FRSTSBTDAT" DATE,
	"UMER_LAS_SBTDAT" DATE,
	"UMER_WKFWISTCID" VARCHAR2(4000),
	"UMER_CNV_ID" VARCHAR2(4000),
	"UMER_OWNRCHNDFLAG" NUMBER(1,0),
	"UMER_OWNRCHNDCNT" NUMBER(10,0),
	"UMER_AUTOUM_AT" DATE,
	"UMER_LAS_RTEDAT" DATE,
	"UMER_ID" NUMBER(19,0),
	"UMET_LAS_CLSDBY" NUMBER(19,0),
	"UMET_LAS_RPNDBY" NUMBER(19,0),
	"UMET_RFNGWKFWTSK" NUMBER(19,0),
	"UMET_PRVSRFNGTSK" NUMBER(19,0),
	"UMET_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"UMET_OWNR" NUMBER(19,0),
	"UMET_PRVSOWNR" NUMBER(19,0),
	"UMET_PRVSSNDR" NUMBER(19,0),
	"UMET_PRVSOWNRPRMN" NUMBER(19,0),
	"UMET_TNFR" NUMBER(19,0),
	"UMET_PRVSTNFR" NUMBER(19,0),
	"UMET_RCPTTRKG" NUMBER(19,0),
	"UMET_LAS_REVW" NUMBER(19,0),
	"UMET_LAS_RTEDTO" NUMBER(19,0),
	"UMET_FRSTOPNDBY" NUMBER(19,0),
	"UMER_LAS_SBTDBY" NUMBER(19,0),
	"UMER_FRSTSBTDBY" NUMBER(19,0),
	"UMER_RFNGWKFWTSK" NUMBER(19,0),
	"UMER_PRVSRFNGTSK" NUMBER(19,0),
	"UMER_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"UMER_OWNR" NUMBER(19,0),
	"UMER_PRVSOWNR" NUMBER(19,0),
	"UMER_PRVSSNDR" NUMBER(19,0),
	"UMER_PRVSOWNRPRMN" NUMBER(19,0),
	"UMER_TNFR" NUMBER(19,0),
	"UMER_PRVSTNFR" NUMBER(19,0),
	"UMER_RCPTTRKG" NUMBER(19,0),
	"UMER_LAS_REVW" NUMBER(19,0),
	"UMER_LAS_RTEDTO" NUMBER(19,0),
	"UMBS_CSTMFLDS" NUMBER(19,0),
	"UMET_UM_EVNTOTCM" NUMBER(19,0),
	"UMET_CLSRRESN" NUMBER(19,0),
	"UMBS_SVTY" NUMBER(19,0),
	"UMBS_PITY" NUMBER(19,0),
	"UMBS_SRC" NUMBER(19,0),
	"UMER_DENLRESN" NUMBER(19,0),
	"UMET_REONRESN" NUMBER(19,0),
	"UMER_RJTNRESN" NUMBER(19,0),
	"UMBS_LTR" NUMBER(19,0),
	"UMBS_TYP" NUMBER(19,0),
	"UMBS_RTNGPEER" NUMBER(19,0),
	"UMBS_RQTR" NUMBER(19,0),
	"UMET_REQT" NUMBER(19,0),
	"UMBS_PMRYPVDR" NUMBER(19,0),
	"UMBS_PFNGPVDR" NUMBER(19,0),
	"UMBS_RQNGPVDR" NUMBER(19,0),
	"UMBS_MEMB" NUMBER(19,0),
	"UMBS_RTNGRCPT" NUMBER(19,0),
	"UMBS_OWNROBST" NUMBER(19,0),
	"UMBS_ID" NUMBER(19,0),
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"UMBS_AUDID" NUMBER,
	"UMBS_PREV_AUDID" NUMBER,
	"UMBS_NEXT_AUDID" NUMBER,
	"UMBS_CNTRCT_ID" VARCHAR2(30),
	"UMBS_FEES_VRFD" NUMBER(1,0) DEFAULT 0,
	"UMBS_RELEASE_OF_INFO" NUMBER(19,0),
	"TRANSACTION_ID" VARCHAR2(4000),
	"UMBS_SRV_AGMT" NUMBER(1,0),
	"UMBS_IN_NETWRK" NUMBER(1,0),
	"UMBS_PAY_AT_MAX" NUMBER(1,0),
	"UMBS_EXT_LMT" NUMBER(1,0),
	"UMBS_CTD" NUMBER(1,0),
	"UMBS_RBRS_MTHD" NUMBER(19,0),
	"UMBS_RBRS_AMT" NUMBER(19,2),
	"UMBS_FEE_TYP" NUMBER(19,0),
	"UMBS_PCT_BLD" NUMBER(19,0),
	"UMBS_DTMN_DUE" DATE,
	"UMBS_ADMT" DATE,
	"UMBS_DISCHRG" DATE,
	"UMBS_AUTH_TYP" NUMBER(19,0),
	"UMBS_ACTY" NUMBER(19,0),
	"UMBS_SVRTY" NUMBER(19,0),
	"UMBS_TRG_DAT_FRM" DATE,
	"UMBS_TRG_DAT_TO" DATE,
	"UMBS_TRG_DAT_DIS" DATE,
	"UMBS_TRG_UNT_TYP" NUMBER(19,0),
	"UMBS_TRG_QNTY" NUMBER(10,0),
	"UMBS_HEALTH_PLAN_RCVD" TIMESTAMP (6),
	"UMBS_DEPT_RCVD" TIMESTAMP (6),
	"UMBS_AUTH_SRC" NUMBER(19,0),
	"UMBS_CLINICALDATAENTRY_ID" NUMBER(19,0)
   ) ;


  CREATE TABLE "THH_C4C"."A_USR"
   (	"USR_SBTDAT" DATE,
	"PRV_PLN_ID" VARCHAR2(4000),
	"PRV_UPN_ID" VARCHAR2(4000),
	"PRV_FED_TAX" VARCHAR2(4000),
	"PRV_TOTLPNTS" NUMBER(10,0),
	"PRV_TOTLPNTSIN_PCTC" NUMBER(10,0),
	"PRV_TOTLPAYRMEMS" NUMBER(10,0),
	"PRV_TOTLPAYRMEMSIN_PCTC" NUMBER(10,0),
	"PRV_ACNGNEW_PNTS" NUMBER(1,0),
	"PRV_ATHDFOR_AUMTDTMN" NUMBER(1,0),
	"PRV_INSCID" VARCHAR2(4000),
	"PRV_IS_ADM" NUMBER(1,0),
	"PRV_PCP_IND" NUMBER(1,0),
	"PRV_ID" NUMBER(19,0),
	"MBUR_DT_OF_DTH" DATE,
	"MBUR_ELBL" NUMBER(1,0),
	"MBUR_COB" NUMBER(1,0),
	"MBUR_COB_NAM" VARCHAR2(4000),
	"MBUR_INSCID_AT_OTHRINSR" VARCHAR2(4000),
	"MBUR_PMRYINSR" NUMBER(1,0),
	"MBUR_CRDTIND" NUMBER(1,0),
	"MBUR_INSCID" VARCHAR2(4000),
	"MBUR_SCL_SCTYNMBR" VARCHAR2(4000),
	"MBUR_CNFTCNCT" NUMBER(1,0),
	"MBUR_DNF_CODE" VARCHAR2(4000),
	"MBUR_ID" NUMBER(19,0),
	"FF_ID" NUMBER(19,0),
	"PAYR_EMPEID" VARCHAR2(4000),
	"PAYR_SCL_SCTYNMBR" VARCHAR2(4000),
	"PAYR_STRTOF_YR" VARCHAR2(4000),
	"PAYR_HREDDT" DATE,
	"PAYR_TMTDDT" DATE,
	"PAYR_THNKHLTHSTRTDT" DATE,
	"PAYR_THNKHLTHEND_DT" DATE,
	"PAYR_WKLDLMITBY_ALL_USR_ROLS" NUMBER(1,0),
	"PAYR_WKLDLMITBY_PMRYUSR_ROLE" NUMBER(1,0),
	"PAYR_WKLDLMITBY" NUMBER(10,0),
	"PAYR_WKLDLMITFNALDCDR" NUMBER(10,0),
	"PAYR_WKLDLMITBY_ROLEBY_SVTY" NUMBER(10,0),
	"PAYR_WKLDLMITBY_TOTLWKLD" NUMBER(10,0),
	"PAYR_WKLDLMTDBY_WORKTYP" NUMBER(10,0),
	"PAYR_REG_DY_OFF_MON" NUMBER(1,0),
	"PAYR_REG_DY_OFF_TUES" NUMBER(1,0),
	"PAYR_REG_DY_OFF_WED" NUMBER(1,0),
	"PAYR_REG_DY_OFF_THRS" NUMBER(1,0),
	"PAYR_REG_DY_OFF_FRI" NUMBER(1,0),
	"PAYR_REG_DY_OFF_SAT" NUMBER(1,0),
	"PAYR_REG_DY_OFF_SUN" NUMBER(1,0),
	"PAYR_SVTYIDX" NUMBER(10,0),
	"PAYR_TOTLWKLD" NUMBER(10,0),
	"PAYR_CASERQTS" NUMBER(10,0),
	"PAYR_CASS" NUMBER(10,0),
	"PAYR_UM_RQTS" NUMBER(10,0),
	"PAYR_UM_EVTS" NUMBER(10,0),
	"PAYR_CM_PRJ_RQTS" NUMBER(10,0),
	"PAYR_CM_PRJS" NUMBER(10,0),
	"PAYR_REVWRQTS" NUMBER(10,0),
	"PAYR_ID" NUMBER(19,0),
	"USR_LAS_DCTDBY" NUMBER(19,0),
	"USR_FRSTATVDBY" NUMBER(19,0),
	"USR_LAS_ATVDBY" NUMBER(19,0),
	"USR_RATNAPVL" NUMBER(19,0),
	"USR_RFNGWKFWTSK" NUMBER(19,0),
	"USR_PRVSRFNGTSK" NUMBER(19,0),
	"USR_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"USR_OWNR" NUMBER(19,0),
	"USR_PRVSOWNR" NUMBER(19,0),
	"USR_PRVSSNDR" NUMBER(19,0),
	"USR_PRVSOWNRPRMN" NUMBER(19,0),
	"USR_TNFR" NUMBER(19,0),
	"USR_PRVSTNFR" NUMBER(19,0),
	"USR_SBTDBY" NUMBER(19,0),
	"MBUR_RCPTTRKG" NUMBER(19,0),
	"MBUR_LAS_REVW" NUMBER(19,0),
	"USR_CSTMFLDS" NUMBER(19,0),
	"PRV_PCP_CAT" NUMBER(19,0),
	"PRV_PVDRTYP" NUMBER(19,0),
	"USR_ECTY" NUMBER(19,0),
	"USR_NAM_SFIX" NUMBER(19,0),
	"USR_NAM_PRFX" NUMBER(19,0),
	"MBUR_RLSPTO_SBCR" NUMBER(19,0),
	"PAYR_CSTMWKLDLMIT" NUMBER(19,0),
	"PAYR_ACTLWKLD" NUMBER(19,0),
	"USR_CNCTINFO" NUMBER(19,0),
	"USR_MRGEMSTR" NUMBER(19,0),
	"PRV_PVDRPAYRDAT" NUMBER(19,0),
	"MBUR_SBCR" NUMBER(19,0),
	"PAYR_PAYRPAYRDAT" NUMBER(19,0),
	"PAYR_BCK1" NUMBER(19,0),
	"PAYR_SVSR" NUMBER(19,0),
	"PAYR_BCK2" NUMBER(19,0),
	"PAYR_BCK3" NUMBER(19,0),
	"PAYR_RGNLSNGS" NUMBER(19,0),
	"PAYR_STCYNOTEPRPS" NUMBER(19,0),
	"MBUR_MEMBPAYRDAT" NUMBER(19,0),
	"USR_PMRYLANG" NUMBER(19,0),
	"CLASSTYPE" VARCHAR2(255),
	"USR_C4C_ID" VARCHAR2(4000),
	"USR_CRTD" DATE,
	"USR_LAS_ACT" NUMBER(10,0),
	"USR_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"USR_OBJ_STT" NUMBER(10,0),
	"USR_VERS" NUMBER(19,0),
	"USR_VSBT" NUMBER(10,0),
	"USR_DLTDDT" DATE,
	"USR_LAS_ACT_BY" NUMBER(19,0),
	"USR_ORIGCRTR" NUMBER(19,0),
	"USR_ORIGCRTRLOGDIN" NUMBER(19,0),
	"USR_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"USR_UNIVID" VARCHAR2(4000),
	"USR_FRSTNAM" VARCHAR2(4000),
	"USR_MDLENAM" VARCHAR2(4000),
	"USR_LAS_NAM" VARCHAR2(4000),
	"USR_DT_OF_BRTH" DATE,
	"USR_GNDRCODE" NUMBER(10,0),
	"USR_FRSTATVD" DATE,
	"USR_LAS_ATVD" DATE,
	"USR_LAS_DCTD" DATE,
	"USR_WKFWISTCID" VARCHAR2(4000),
	"USR_CNV_ID" VARCHAR2(4000),
	"USR_OWNRCHNDFLAG" NUMBER(1,0),
	"USR_OWNRCHNDCNT" NUMBER(10,0),
	"USR_ID" NUMBER(19,0),
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"USR_AUDID" NUMBER,
	"USR_PREV_AUDID" NUMBER,
	"USR_NEXT_AUDID" NUMBER,
	"MBUR_MEDICAID" VARCHAR2(4000),
	"MBUR_HICNID" VARCHAR2(4000),
	"PRV_SPLRTYP" NUMBER(19,0),
	"MBUR_MEDICAID_RECERT_DATE" DATE,
	"MBUR_RESTRICTED_RCPNT_PRGRM" NUMBER(1,0),
	"MBUR_MBI" VARCHAR2(25),
	"MBUR_ENDANGERED" NUMBER(1,0),
	"MBUR_SAFEWORD" VARCHAR2(250)
   ) ;


  CREATE TABLE "THH_C4C"."MV_PATID_CM_COND_PROVIDER"
   (	"MEMBER_ID" NUMBER,
	"CARE_GIVER" NUMBER,
	"VALID_FROM" DATE,
	"VALID_TO" DATE,
	"PRAS_STRTDT" DATE,
	"PRAS_END_DT" DATE
   ) ;


  CREATE INDEX "THH_C4C"."AX_APBL_ACTLUNTS" ON "THH_C4C"."A_APBL" ("APBL_ACTLUNTS")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_APRDUNTS" ON "THH_C4C"."A_APBL" ("APBL_APRDUNTS")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_CLASSTYPE" ON "THH_C4C"."A_APBL" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_CRTD" ON "THH_C4C"."A_APBL" ("APBL_CRTD")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_DENLRESN" ON "THH_C4C"."A_APBL" ("APBL_DENLRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_NEXT_AUDID" ON "THH_C4C"."A_APBL" ("APBL_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_OBJ_STT" ON "THH_C4C"."A_APBL" ("APBL_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_PREV_AUDID" ON "THH_C4C"."A_APBL" ("APBL_PREV_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_RQTDUNTS" ON "THH_C4C"."A_APBL" ("APBL_RQTDUNTS")
  ;


  CREATE INDEX "THH_C4C"."AX_APBL_UMPARAMS" ON "THH_C4C"."A_APBL" ("APBL_ID", "APBL_AUDID", "VALID_FROM", "VALID_TO", "APBL_APRDQNTY", "MSRV_SRVCDGIS", "APBL_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_CLSRRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_CLSRRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_FRSTOPNDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_FRSTOPNDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_LAS_CLSDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_LAS_CLSDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_LAS_REVW" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_LAS_RPNDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_LAS_RPNDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_OWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRJ_OTCM" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRJ_OTCM")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRVSOWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRVSOWNRPRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRVSRFNGTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRVSSNDR" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_PRVSTNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_RCPTTRKG" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_REONRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_REONRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_REQT" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_REQT")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_RFNGWKFWTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CASE_TNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CASE_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CBDG_MDCLCLM" ON "THH_C4C"."A_MEMBDGISBASE" ("CBDG_MDCLCLM")
  ;


  CREATE INDEX "THH_C4C"."AX_CFDS_AMTN" ON "THH_C4C"."A_MEMBDGISBASE" ("CFDS_AMTN")
  ;


  CREATE INDEX "THH_C4C"."AX_CFDS_CM_TMPT" ON "THH_C4C"."A_MEMBDGISBASE" ("CFDS_CM_TMPT")
  ;


  CREATE INDEX "THH_C4C"."AX_CFDS_SENTASMT" ON "THH_C4C"."A_MEMBDGISBASE" ("CFDS_SENTASMT")
  ;


  CREATE INDEX "THH_C4C"."AX_CFDS_THE_BRNCACT" ON "THH_C4C"."A_MEMBDGISBASE" ("CFDS_THE_BRNCACT")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_CLASSTYPE" ON "THH_C4C"."A_CM_BASEBASE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_CRTD" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_CRTD")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_CSTMFLDS" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_NEXT_AUDID" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_OBJ_STT" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_OWNROBST" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_OWNROBST")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_PITY" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_PITY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_PMRYPVDR" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_PMRYPVDR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_PREV_AUDID" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_PREV_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_RESN" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_RESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_RTNGRCPT" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_RTNGRCPT")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_SRC" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_SRC")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_SVTY" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_SVTY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBB_TYP" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_TYP")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBS_MEMB" ON "THH_C4C"."A_CM_BASEBASE" ("CMBS_MEMB")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBS_PAT_ID_QRY" ON "THH_C4C"."A_CM_BASEBASE" ("CMBS_PAT_ID_QRY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBS_QRY_STTS" ON "THH_C4C"."A_CM_BASEBASE" ("CMBS_QRY_STTS")
  ;


  CREATE INDEX "THH_C4C"."AX_CMBS_TMPT" ON "THH_C4C"."A_CM_BASEBASE" ("CMBS_TMPT")
  ;


  CREATE INDEX "THH_C4C"."AX_CMDI_CM_BASE" ON "THH_C4C"."A_MEMBDGISBASE" ("CMDI_CM_BASE")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_DENLRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_DENLRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_FRSTSBTDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_FRSTSBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_LAS_REVW" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_LAS_RTEDTO" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_LAS_RTEDTO")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_LAS_SBTDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_LAS_SBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_OWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_PRVSOWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_PRVSOWNRPRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_PRVSRFNGTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_PRVSSNDR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_PRVSTNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_RCPTTRKG" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_RFNGWKFWTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_RJTNRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_RJTNRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_RTNGPEER" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_RTNGPEER")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_RTNGRCPT" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_RTNGRCPT")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPQ_TNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPQ_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_CLSRRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_CLSRRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_FRSTOPNDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_FRSTOPNDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_LAS_CLSDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_LAS_CLSDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_LAS_REVW" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_LAS_RPNDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_LAS_RPNDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_OWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRJ_OTCM" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRJ_OTCM")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRVSOWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRVSOWNRPRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRVSRFNGTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRVSSNDR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_PRVSTNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_RCPTTRKG" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_REONRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_REONRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_REQT" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_REQT")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_RFNGWKFWTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CMPR_TNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CMPR_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CMTB_AMTN" ON "THH_C4C"."A_CM_BASEBASE" ("CMTB_AMTN")
  ;


  CREATE INDEX "THH_C4C"."AX_CPAS_CM_BASE" ON "THH_C4C"."A_PVDRASTN" ("CPAS_CM_BASE")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_DENLRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_DENLRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_FRSTSBTDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_FRSTSBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_LAS_REVW" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_LAS_RTEDTO" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_LAS_RTEDTO")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_LAS_SBTDBY" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_LAS_SBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_OWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_PRVSOWNR" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_PRVSOWNRPRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_PRVSRFNGTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_PRVSSNDR" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_PRVSTNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_RCPTTRKG" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_RFNGWKFWTSK" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_RJTNRESN" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_RJTNRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_RTNGPEER" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_RTNGPEER")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_RTNGRCPT" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_RTNGRCPT")
  ;


  CREATE INDEX "THH_C4C"."AX_CSRQ_TNFR" ON "THH_C4C"."A_CM_BASEBASE" ("CSRQ_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_CLASSTYPE" ON "THH_C4C"."A_MEMBDGISBASE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_CRTD" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_CRTD")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_CSTMFLDS" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_DGIS" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_DGIS")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_NEXT_AUDID" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_OBJ_STT" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_MBDB_PREV_AUDID" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_PREV_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_MBUR_LAS_REVW" ON "THH_C4C"."A_USR" ("MBUR_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_MBUR_MEMBPAYRDAT" ON "THH_C4C"."A_USR" ("MBUR_MEMBPAYRDAT")
  ;


  CREATE INDEX "THH_C4C"."AX_MBUR_RCPTTRKG" ON "THH_C4C"."A_USR" ("MBUR_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_MBUR_RLSPTO_SBCR" ON "THH_C4C"."A_USR" ("MBUR_RLSPTO_SBCR")
  ;


  CREATE INDEX "THH_C4C"."AX_MBUR_SBCR" ON "THH_C4C"."A_USR" ("MBUR_SBCR")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_CAUDBY" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_CAUDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_GRP" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_GRP")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_MEMB" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_MEMB")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_OWNR" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_PRVSOWNR" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_PRVSOWNRPRMN" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_PRVSRFNGTSK" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_PRVSSNDR" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_PRVSTNFR" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_RFNGWKFWTSK" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_SRC__ASMTCARECALC" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_SRC__ASMTCARECALC")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_SRC__PAT_ID_QRY" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_SRC__PAT_ID_QRY")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_TAKNASMTCC" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_TAKNASMTCC")
  ;


  CREATE INDEX "THH_C4C"."AX_MDSS_TNFR" ON "THH_C4C"."A_MEMBDGISBASE" ("MDSS_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_MPAS_DRUGCLM" ON "THH_C4C"."A_PVDRASTN" ("MPAS_DRUGCLM")
  ;


  CREATE INDEX "THH_C4C"."AX_MPAS_MDCLCLM" ON "THH_C4C"."A_PVDRASTN" ("MPAS_MDCLCLM")
  ;


  CREATE INDEX "THH_C4C"."AX_MPAS_MEMB" ON "THH_C4C"."A_PVDRASTN" ("MPAS_MEMB")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_BED_TYP" ON "THH_C4C"."A_APBL" ("MSRV_BED_TYP")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_CSTMFLDS" ON "THH_C4C"."A_APBL" ("MSRV_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_LAS_EXTN" ON "THH_C4C"."A_APBL" ("MSRV_LAS_EXTN")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_MDCLSRVCTYP" ON "THH_C4C"."A_APBL" ("MSRV_MDCLSRVCTYP")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_MNLYDRMDBY" ON "THH_C4C"."A_APBL" ("MSRV_MNLYDRMDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_OWNR" ON "THH_C4C"."A_APBL" ("MSRV_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PLCEOF_SRVCTYP" ON "THH_C4C"."A_APBL" ("MSRV_PLCEOF_SRVCTYP")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PRVSOWNR" ON "THH_C4C"."A_APBL" ("MSRV_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PRVSOWNRPRMN" ON "THH_C4C"."A_APBL" ("MSRV_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PRVSRFNGTSK" ON "THH_C4C"."A_APBL" ("MSRV_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_APBL" ("MSRV_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PRVSSNDR" ON "THH_C4C"."A_APBL" ("MSRV_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PRVSTNFR" ON "THH_C4C"."A_APBL" ("MSRV_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_PVDRASTN" ON "THH_C4C"."A_APBL" ("MSRV_PVDRASTN")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_RFNGWKFWTSK" ON "THH_C4C"."A_APBL" ("MSRV_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_SNP" ON "THH_C4C"."A_APBL" ("MSRV_SNP")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_SRVCDGIS" ON "THH_C4C"."A_APBL" ("MSRV_SRVCDGIS")
  ;


  CREATE INDEX "THH_C4C"."AX_MSRV_TNFR" ON "THH_C4C"."A_APBL" ("MSRV_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_ACTLWKLD" ON "THH_C4C"."A_USR" ("PAYR_ACTLWKLD")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_BCK1" ON "THH_C4C"."A_USR" ("PAYR_BCK1")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_BCK2" ON "THH_C4C"."A_USR" ("PAYR_BCK2")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_BCK3" ON "THH_C4C"."A_USR" ("PAYR_BCK3")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_CSTMWKLDLMIT" ON "THH_C4C"."A_USR" ("PAYR_CSTMWKLDLMIT")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_PAYRPAYRDAT" ON "THH_C4C"."A_USR" ("PAYR_PAYRPAYRDAT")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_RGNLSNGS" ON "THH_C4C"."A_USR" ("PAYR_RGNLSNGS")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_STCYNOTEPRPS" ON "THH_C4C"."A_USR" ("PAYR_STCYNOTEPRPS")
  ;


  CREATE INDEX "THH_C4C"."AX_PAYR_SVSR" ON "THH_C4C"."A_USR" ("PAYR_SVSR")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_CLASSTYPE" ON "THH_C4C"."A_PVDRASTN" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_CRTD" ON "THH_C4C"."A_PVDRASTN" ("PRAS_CRTD")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_NEXT_AUDID" ON "THH_C4C"."A_PVDRASTN" ("PRAS_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_OBJ_STT" ON "THH_C4C"."A_PVDRASTN" ("PRAS_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_PREV_AUDID" ON "THH_C4C"."A_PVDRASTN" ("PRAS_PREV_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_PVDR" ON "THH_C4C"."A_PVDRASTN" ("PRAS_PVDR")
  ;


  CREATE INDEX "THH_C4C"."AX_PRAS_ROLE" ON "THH_C4C"."A_PVDRASTN" ("PRAS_ROLE")
  ;


  CREATE INDEX "THH_C4C"."AX_PRV_PCP_CAT" ON "THH_C4C"."A_USR" ("PRV_PCP_CAT")
  ;


  CREATE INDEX "THH_C4C"."AX_PRV_PVDRPAYRDAT" ON "THH_C4C"."A_USR" ("PRV_PVDRPAYRDAT")
  ;


  CREATE INDEX "THH_C4C"."AX_PRV_PVDRTYP" ON "THH_C4C"."A_USR" ("PRV_PVDRTYP")
  ;


  CREATE INDEX "THH_C4C"."AX_UMAD_UMBS" ON "THH_C4C"."A_MEMBDGISBASE" ("UMAD_UMBS")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_CLASSTYPE" ON "THH_C4C"."A_UM_BASE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_CRTD" ON "THH_C4C"."A_UM_BASE" ("UMBS_CRTD")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_CSTMFLDS" ON "THH_C4C"."A_UM_BASE" ("UMBS_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_LTR" ON "THH_C4C"."A_UM_BASE" ("UMBS_LTR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_MEMB" ON "THH_C4C"."A_UM_BASE" ("UMBS_MEMB")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_NEXT_AUDID" ON "THH_C4C"."A_UM_BASE" ("UMBS_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_OBJ_STT" ON "THH_C4C"."A_UM_BASE" ("UMBS_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_OWNROBST" ON "THH_C4C"."A_UM_BASE" ("UMBS_OWNROBST")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_PFNGPVDR" ON "THH_C4C"."A_UM_BASE" ("UMBS_PFNGPVDR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_PITY" ON "THH_C4C"."A_UM_BASE" ("UMBS_PITY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_PMRYPVDR" ON "THH_C4C"."A_UM_BASE" ("UMBS_PMRYPVDR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_PREV_AUDID" ON "THH_C4C"."A_UM_BASE" ("UMBS_PREV_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_RQNGPVDR" ON "THH_C4C"."A_UM_BASE" ("UMBS_RQNGPVDR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_RQTR" ON "THH_C4C"."A_UM_BASE" ("UMBS_RQTR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_RTNGPEER" ON "THH_C4C"."A_UM_BASE" ("UMBS_RTNGPEER")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_RTNGRCPT" ON "THH_C4C"."A_UM_BASE" ("UMBS_RTNGRCPT")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_SRC" ON "THH_C4C"."A_UM_BASE" ("UMBS_SRC")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_SVTY" ON "THH_C4C"."A_UM_BASE" ("UMBS_SVTY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMBS_TYP" ON "THH_C4C"."A_UM_BASE" ("UMBS_TYP")
  ;


  CREATE INDEX "THH_C4C"."AX_UMDS_DGISUM_EVNT" ON "THH_C4C"."A_MEMBDGISBASE" ("UMDS_DGISUM_EVNT")
  ;


  CREATE INDEX "THH_C4C"."AX_UMDS_SNP" ON "THH_C4C"."A_MEMBDGISBASE" ("UMDS_SNP")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_DENLRESN" ON "THH_C4C"."A_UM_BASE" ("UMER_DENLRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_FRSTSBTDBY" ON "THH_C4C"."A_UM_BASE" ("UMER_FRSTSBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_LAS_REVW" ON "THH_C4C"."A_UM_BASE" ("UMER_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_LAS_RTEDTO" ON "THH_C4C"."A_UM_BASE" ("UMER_LAS_RTEDTO")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_LAS_SBTDBY" ON "THH_C4C"."A_UM_BASE" ("UMER_LAS_SBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_OWNR" ON "THH_C4C"."A_UM_BASE" ("UMER_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_PRVSOWNR" ON "THH_C4C"."A_UM_BASE" ("UMER_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_PRVSOWNRPRMN" ON "THH_C4C"."A_UM_BASE" ("UMER_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_PRVSRFNGTSK" ON "THH_C4C"."A_UM_BASE" ("UMER_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_UM_BASE" ("UMER_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_PRVSSNDR" ON "THH_C4C"."A_UM_BASE" ("UMER_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_PRVSTNFR" ON "THH_C4C"."A_UM_BASE" ("UMER_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_RCPTTRKG" ON "THH_C4C"."A_UM_BASE" ("UMER_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_RFNGWKFWTSK" ON "THH_C4C"."A_UM_BASE" ("UMER_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_RJTNRESN" ON "THH_C4C"."A_UM_BASE" ("UMER_RJTNRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMER_TNFR" ON "THH_C4C"."A_UM_BASE" ("UMER_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_CLSRRESN" ON "THH_C4C"."A_UM_BASE" ("UMET_CLSRRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_FRSTOPNDBY" ON "THH_C4C"."A_UM_BASE" ("UMET_FRSTOPNDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_LAS_CLSDBY" ON "THH_C4C"."A_UM_BASE" ("UMET_LAS_CLSDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_LAS_REVW" ON "THH_C4C"."A_UM_BASE" ("UMET_LAS_REVW")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_LAS_RPNDBY" ON "THH_C4C"."A_UM_BASE" ("UMET_LAS_RPNDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_LAS_RTEDTO" ON "THH_C4C"."A_UM_BASE" ("UMET_LAS_RTEDTO")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_OWNR" ON "THH_C4C"."A_UM_BASE" ("UMET_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_PRVSOWNR" ON "THH_C4C"."A_UM_BASE" ("UMET_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_PRVSOWNRPRMN" ON "THH_C4C"."A_UM_BASE" ("UMET_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_PRVSRFNGTSK" ON "THH_C4C"."A_UM_BASE" ("UMET_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_UM_BASE" ("UMET_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_PRVSSNDR" ON "THH_C4C"."A_UM_BASE" ("UMET_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_PRVSTNFR" ON "THH_C4C"."A_UM_BASE" ("UMET_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_RCPTTRKG" ON "THH_C4C"."A_UM_BASE" ("UMET_RCPTTRKG")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_REONRESN" ON "THH_C4C"."A_UM_BASE" ("UMET_REONRESN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_REQT" ON "THH_C4C"."A_UM_BASE" ("UMET_REQT")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_RFNGWKFWTSK" ON "THH_C4C"."A_UM_BASE" ("UMET_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_TNFR" ON "THH_C4C"."A_UM_BASE" ("UMET_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMET_UM_EVNTOTCM" ON "THH_C4C"."A_UM_BASE" ("UMET_UM_EVNTOTCM")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_DCLYXTDD" ON "THH_C4C"."A_APBL" ("UMXT_DCLYXTDD")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_MNLYDRMDBY" ON "THH_C4C"."A_APBL" ("UMXT_MNLYDRMDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_OWNR" ON "THH_C4C"."A_APBL" ("UMXT_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRNTEVNT" ON "THH_C4C"."A_APBL" ("UMXT_PRNTEVNT")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRVSOWNR" ON "THH_C4C"."A_APBL" ("UMXT_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRVSOWNRPRMN" ON "THH_C4C"."A_APBL" ("UMXT_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRVSRFNGTSK" ON "THH_C4C"."A_APBL" ("UMXT_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_APBL" ("UMXT_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRVSSNDR" ON "THH_C4C"."A_APBL" ("UMXT_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_PRVSTNFR" ON "THH_C4C"."A_APBL" ("UMXT_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_RFNGWKFWTSK" ON "THH_C4C"."A_APBL" ("UMXT_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_TNFR" ON "THH_C4C"."A_APBL" ("UMXT_TNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_UMXT_XTDD" ON "THH_C4C"."A_APBL" ("UMXT_XTDD")
  ;


  CREATE INDEX "THH_C4C"."AX_UPAS_PVDRUM_BASE" ON "THH_C4C"."A_PVDRASTN" ("UPAS_PVDRUM_BASE")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_CLASSTYPE" ON "THH_C4C"."A_USR" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_CNCTINFO" ON "THH_C4C"."A_USR" ("USR_CNCTINFO")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_CRTD" ON "THH_C4C"."A_USR" ("USR_CRTD")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_CSTMFLDS" ON "THH_C4C"."A_USR" ("USR_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_ECTY" ON "THH_C4C"."A_USR" ("USR_ECTY")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_FROMTO" ON "THH_C4C"."A_USR" ("USR_ID", "VALID_FROM", "VALID_TO", "USR_MRGEMSTR", "USR_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_FRSTATVDBY" ON "THH_C4C"."A_USR" ("USR_FRSTATVDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_LAS_ATVDBY" ON "THH_C4C"."A_USR" ("USR_LAS_ATVDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_LAS_DCTDBY" ON "THH_C4C"."A_USR" ("USR_LAS_DCTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_MRGEMSTR" ON "THH_C4C"."A_USR" ("USR_MRGEMSTR")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_NAM_PRFX" ON "THH_C4C"."A_USR" ("USR_NAM_PRFX")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_NAM_SFIX" ON "THH_C4C"."A_USR" ("USR_NAM_SFIX")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_NEXT_AUDID" ON "THH_C4C"."A_USR" ("USR_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_OBJ_STT" ON "THH_C4C"."A_USR" ("USR_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_OWNR" ON "THH_C4C"."A_USR" ("USR_OWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PMRYLANG" ON "THH_C4C"."A_USR" ("USR_PMRYLANG")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PREV_AUDID" ON "THH_C4C"."A_USR" ("USR_PREV_AUDID")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PRVSOWNR" ON "THH_C4C"."A_USR" ("USR_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PRVSOWNRPRMN" ON "THH_C4C"."A_USR" ("USR_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PRVSRFNGTSK" ON "THH_C4C"."A_USR" ("USR_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PRVSRFNGTSK_PRMN" ON "THH_C4C"."A_USR" ("USR_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PRVSSNDR" ON "THH_C4C"."A_USR" ("USR_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_PRVSTNFR" ON "THH_C4C"."A_USR" ("USR_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_RATNAPVL" ON "THH_C4C"."A_USR" ("USR_RATNAPVL")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_RFNGWKFWTSK" ON "THH_C4C"."A_USR" ("USR_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_SBTDBY" ON "THH_C4C"."A_USR" ("USR_SBTDBY")
  ;


  CREATE INDEX "THH_C4C"."AX_USR_TNFR" ON "THH_C4C"."A_USR" ("USR_TNFR")
  ;


  CREATE INDEX "THH_C4C"."A_APBL_IX_TUNE1" ON "THH_C4C"."A_APBL" ("APBL_C4C_ID", "UMXT_XTDD")
  ;


  CREATE INDEX "THH_C4C"."A_CM_BASEBASE_IX_TUNE1" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_LAS_ACT", "CMBB_LAS_ACT_BY")
  ;


  CREATE INDEX "THH_C4C"."A_CM_BASEBASE_IX_TUNE2" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_LAS_ACT", "CMPQ_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."A_CM_BASEBASE_IX_VALID_FROM_ID" ON "THH_C4C"."A_CM_BASEBASE" ("VALID_FROM", "CMBB_ID")
  ;


  CREATE INDEX "THH_C4C"."A_MEMBDGISBASE_IX_TUNE1" ON "THH_C4C"."A_MEMBDGISBASE" ("UMDS_ID", "UMDS_DGISUM_EVNT")
  ;


  CREATE INDEX "THH_C4C"."A_UM_BASE_IX_TUNE1" ON "THH_C4C"."A_UM_BASE" ("UMBS_LAS_ACT", "UMBS_LAS_ACT_BY")
  ;


  CREATE INDEX "THH_C4C"."A_UM_BASE_IX_TUNE2" ON "THH_C4C"."A_UM_BASE" ("UMBS_LAS_ACT", "UMER_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."A_USR_IX_MBUR_ID_CLASSTYPE" ON "THH_C4C"."A_USR" ("MBUR_ID", "CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_A_APBL_IDVALIDFROM" ON "THH_C4C"."A_APBL" ("APBL_ID", "VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_A_CMBB_IDVALIDFROM" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_ID", "VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_A_MBDB_IDVALIDFROM" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_ID", "VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_A_PRAS_IDVALIDFROM" ON "THH_C4C"."A_PVDRASTN" ("PRAS_ID", "VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_A_UMBS_IDVALIDFROM" ON "THH_C4C"."A_UM_BASE" ("UMBS_ID", "VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_A_USR_IDVALIDFROM" ON "THH_C4C"."A_USR" ("USR_ID", "VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_MPCCPR_CARE_GIVER" ON "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("CARE_GIVER")
  ;


  CREATE INDEX "THH_C4C"."IX_MPCCPR_ENDDATE" ON "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("PRAS_END_DT")
  ;


  CREATE INDEX "THH_C4C"."IX_MPCCPR_MEMBER_ID" ON "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("MEMBER_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_MPCCPR_STARTDATE" ON "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("PRAS_STRTDT")
  ;


  CREATE INDEX "THH_C4C"."IX_MPCCPR_VALID_FROM" ON "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("VALID_FROM")
  ;


  CREATE INDEX "THH_C4C"."IX_MPCCPR_VALID_TO" ON "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("VALID_TO")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PA_APBL" ON "THH_C4C"."A_APBL" ("APBL_AUDID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PA_CM_BASEBASE" ON "THH_C4C"."A_CM_BASEBASE" ("CMBB_AUDID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PA_MEMBDGISBASE" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_AUDID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PA_PVDRASTN" ON "THH_C4C"."A_PVDRASTN" ("PRAS_AUDID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PA_UM_BASE" ON "THH_C4C"."A_UM_BASE" ("UMBS_AUDID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PA_USR" ON "THH_C4C"."A_USR" ("USR_AUDID")
  ;


  CREATE INDEX "THH_C4C"."PERFAAPBLX4" ON "THH_C4C"."A_APBL" ("APBL_ID", "APBL_AUDID", "APBL_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."PERFAUSERX16" ON "THH_C4C"."A_USR" ("USR_ID", "USR_AUDID", "USR_NEXT_AUDID")
  ;


  CREATE INDEX "THH_C4C"."PERFMEMBDGISX12" ON "THH_C4C"."A_MEMBDGISBASE" ("MBDB_ID", "MBDB_AUDID", "MBDB_NEXT_AUDID")
  ;


  CREATE MATERIALIZED VIEW "THH_C4C"."MV_PATID_CM_COND_PROVIDER" ("MEMBER_ID", "CARE_GIVER", "VALID_FROM", "VALID_TO", "PRAS_STRTDT", "PRAS_END_DT")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  BUILD IMMEDIATE
  USING INDEX
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT get_aud_mrgmstr(member_id, valid_from, valid_to) member_id,
       get_aud_mrgmstr(care_giver, valid_from, valid_to) care_giver,
       valid_from,
       valid_to,
       PRAS_STRTDT,
       PRAS_END_DT
  FROM (SELECT a_cm_basebase.cmbs_memb member_id,
               a_pvdrastn.pras_pvdr care_giver,
               GREATEST(a_pvdrastn.valid_from, NVL(a_cm_basebase.valid_from, TO_DATE('1800-01-01', 'YYYY-MM-DD'))) valid_from,
               CASE WHEN a_pvdrastn.valid_to IS NULL AND a_cm_basebase.valid_to IS NULL THEN
                       TO_DATE('2999-01-01', 'YYYY-MM-DD')
                   WHEN a_pvdrastn.valid_to IS NOT NULL AND a_cm_basebase.valid_to IS NOT NULL THEN
                       LEAST(a_pvdrastn.valid_to, a_cm_basebase.valid_to)
                   WHEN a_pvdrastn.valid_to IS NULL THEN  a_cm_basebase.valid_to
                   ELSE a_pvdrastn.valid_to
               END valid_to,
               a_pvdrastn.PRAS_STRTDT,
			   a_pvdrastn.PRAS_END_DT
          FROM a_pvdrastn
               INNER JOIN a_cm_basebase
                   ON a_pvdrastn.cpas_cm_base = a_cm_basebase.cmbb_id
                  AND ((a_pvdrastn.valid_from >= a_cm_basebase.valid_from
                    AND (a_pvdrastn.valid_from <= a_cm_basebase.valid_to OR a_cm_basebase.valid_to IS NULL))
                    OR (a_pvdrastn.valid_from <= a_cm_basebase.valid_from
                    AND (a_pvdrastn.valid_to >= a_cm_basebase.valid_from OR a_pvdrastn.valid_to IS NULL)))
                  AND a_pvdrastn.pras_obj_stt != 2
                  AND a_cm_basebase.cmbb_obj_stt != 2
                  AND a_pvdrastn.pras_pvdr IS NOT NULL
                  AND a_cm_basebase.cmbs_memb IS NOT NULL
        UNION
        SELECT a_usr.mbur_id member_id,
               a_pvdrastn.pras_pvdr care_giver,
               GREATEST(a_pvdrastn.valid_from, NVL(a_usr.valid_from, TO_DATE('1800-01-01', 'YYYY-MM-DD'))) valid_from,
               CASE WHEN a_pvdrastn.valid_to IS NULL AND a_usr.valid_to IS NULL THEN TO_DATE('2999-01-01', 'YYYY-MM-DD')
                   WHEN a_pvdrastn.valid_to IS NOT NULL AND a_usr.valid_to IS NOT NULL THEN LEAST(a_pvdrastn.valid_to, a_usr.valid_to)
                   WHEN a_pvdrastn.valid_to IS NULL THEN a_usr.valid_to
                   ELSE a_pvdrastn.valid_to
               END valid_to,
          	   a_pvdrastn.PRAS_STRTDT,
			   a_pvdrastn.PRAS_END_DT
          FROM a_pvdrastn
               INNER JOIN a_usr
                   ON a_pvdrastn.mpas_memb = a_usr.mbur_id
                  AND ((a_pvdrastn.valid_from >= a_usr.valid_from
                    AND (a_pvdrastn.valid_from <= a_usr.valid_to OR a_usr.valid_to IS NULL))
                    OR (a_pvdrastn.valid_from <= a_usr.valid_from
                    AND (a_pvdrastn.valid_to >= a_usr.valid_from OR a_pvdrastn.valid_to IS NULL)))
                  AND a_pvdrastn.pras_obj_stt != 2
                  AND a_pvdrastn.pras_pvdr IS NOT NULL
        UNION
        SELECT a_cm_basebase.cmbs_memb member_id,
               a_cm_basebase.cmbb_pmrypvdr care_giver,
               a_cm_basebase.valid_from,
               a_cm_basebase.valid_to,
               null as PRAS_STRTDT,
			   null as PRAS_END_DT
          FROM a_cm_basebase
         WHERE a_cm_basebase.cmbb_obj_stt != 2
           AND a_cm_basebase.cmbb_pmrypvdr IS NOT NULL
           AND a_cm_basebase.cmbs_memb IS NOT NULL
UNION
  SELECT a_um_base.umbs_memb member_id,
               a_pvdrastn.pras_pvdr care_giver,
               GREATEST(a_pvdrastn.valid_from, NVL(a_um_base.valid_from, TO_DATE('1800-01-01', 'YYYY-MM-DD'))) valid_from,
               CASE WHEN a_pvdrastn.valid_to IS NULL AND a_um_base.valid_to IS NULL THEN
                       TO_DATE('2999-01-01', 'YYYY-MM-DD')
                   WHEN a_pvdrastn.valid_to IS NOT NULL AND a_um_base.valid_to IS NOT NULL THEN
                       LEAST(a_pvdrastn.valid_to, a_um_base.valid_to)
                   WHEN a_pvdrastn.valid_to IS NULL THEN  a_um_base.valid_to
                   ELSE a_pvdrastn.valid_to
               END valid_to,
               a_pvdrastn.PRAS_STRTDT,
			   a_pvdrastn.PRAS_END_DT
          FROM a_pvdrastn
               INNER JOIN a_um_base
                   ON a_pvdrastn.UPAS_PVDRUM_BASE = a_um_base.umbs_id
                  AND ((a_pvdrastn.valid_from >= a_um_base.valid_from
                    AND (a_pvdrastn.valid_from <= a_um_base.valid_to OR a_um_base.valid_to IS NULL))
                    OR (a_pvdrastn.valid_from <= a_um_base.valid_from
                    AND (a_pvdrastn.valid_to >= a_um_base.valid_from OR a_pvdrastn.valid_to IS NULL)))
                  AND a_pvdrastn.pras_obj_stt != 2
                  AND a_um_base.umbs_obj_stt != 2
                  AND a_pvdrastn.pras_pvdr IS NOT NULL
                  AND a_um_base.umbs_memb IS NOT NULL
        UNION
        SELECT a_usr.mbur_id member_id,
               a_pvdrastn.pras_pvdr care_giver,
               GREATEST(a_pvdrastn.valid_from, NVL(a_usr.valid_from, TO_DATE('1800-01-01', 'YYYY-MM-DD'))) valid_from,
               CASE WHEN a_pvdrastn.valid_to IS NULL AND a_usr.valid_to IS NULL THEN TO_DATE('2999-01-01', 'YYYY-MM-DD')
                   WHEN a_pvdrastn.valid_to IS NOT NULL AND a_usr.valid_to IS NOT NULL THEN LEAST(a_pvdrastn.valid_to, a_usr.valid_to)
                   WHEN a_pvdrastn.valid_to IS NULL THEN a_usr.valid_to
                   ELSE a_pvdrastn.valid_to
               END valid_to,
               a_pvdrastn.PRAS_STRTDT,
		       a_pvdrastn.PRAS_END_DT
          FROM a_pvdrastn
               INNER JOIN a_usr
                   ON a_pvdrastn.mpas_memb = a_usr.mbur_id
                  AND ((a_pvdrastn.valid_from >= a_usr.valid_from
                    AND (a_pvdrastn.valid_from <= a_usr.valid_to OR a_usr.valid_to IS NULL))
                    OR (a_pvdrastn.valid_from <= a_usr.valid_from
                    AND (a_pvdrastn.valid_to >= a_usr.valid_from OR a_pvdrastn.valid_to IS NULL)))
                  AND a_pvdrastn.pras_obj_stt != 2
                  AND a_pvdrastn.pras_pvdr IS NOT NULL
        UNION
        SELECT a_um_base.umbs_memb member_id,
               a_um_base.umbs_pmrypvdr care_giver, -- PrimaryProvider CP-287
               a_um_base.valid_from,
               a_um_base.valid_to,
               null as PRAS_STRTDT,
			   null as PRAS_END_DT
          FROM a_um_base
         WHERE a_um_base.umbs_obj_stt != 2
           AND a_um_base.umbs_pfngpvdr IS NOT NULL
           AND a_um_base.umbs_memb IS NOT NULL)
--
--
	UNION
		SELECT
		  a_membdgisbase.mdss_memb member_id,
		  a_pvdrastn.pras_pvdr care_giver,
		  GREATEST(a_pvdrastn.valid_from, NVL(a_apbl.valid_from, TO_DATE('1800-01-01', 'YYYY-MM-DD'))) valid_from,
		  CASE
		    WHEN a_pvdrastn.valid_to IS NULL AND a_apbl.valid_to IS NULL THEN TO_DATE('2999-01-01', 'YYYY-MM-DD')
		    WHEN a_pvdrastn.valid_to IS NOT NULL AND a_apbl.valid_to IS NOT NULL THEN LEAST(a_pvdrastn.valid_to, a_apbl.valid_to)
		    WHEN a_pvdrastn.valid_to IS NULL THEN  a_apbl.valid_to
		    ELSE a_pvdrastn.valid_to
		  END valid_to,
		  a_pvdrastn.PRAS_STRTDT,
		  a_pvdrastn.PRAS_END_DT
		  FROM a_pvdrastn
		    INNER JOIN a_apbl
		      ON a_pvdrastn.mspa_id = a_apbl.msrv_pvdrastn
		        AND ((a_pvdrastn.valid_from >= a_apbl.valid_from
		          AND (a_pvdrastn.valid_from <= a_apbl.valid_to OR a_apbl.valid_to IS NULL))
		          OR (a_pvdrastn.valid_from <= a_apbl.valid_from
		          AND (a_pvdrastn.valid_to >= a_apbl.valid_from OR a_pvdrastn.valid_to IS NULL)))
		        AND a_pvdrastn.pras_obj_stt != 2
		        AND a_apbl.apbl_obj_stt != 2
		        AND a_pvdrastn.pras_pvdr IS NOT NULL
		    INNER JOIN a_membdgisbase
		      ON a_pvdrastn.upas_pvdrum_base = a_membdgisbase.umds_dgisum_evnt
            AND ( (a_pvdrastn.valid_from >= a_membdgisbase.valid_from
		          AND (a_pvdrastn.valid_from <= a_membdgisbase.valid_to OR a_membdgisbase.valid_to IS NULL) )
		          OR (a_pvdrastn.valid_from <= a_membdgisbase.valid_from
		          AND (a_pvdrastn.valid_to >= a_membdgisbase.valid_from OR a_pvdrastn.valid_to IS NULL)) )
		        AND a_apbl.msrv_srvcdgis = a_membdgisbase.mdss_id;

