
  CREATE TABLE "THH_C4C"."T_DDL_ITEM"
   (	"CLASSTYPE" VARCHAR2(255),
	"DDLI_C4C_ID" VARCHAR2(4000),
	"DDLI_CRTD" DATE,
	"DDLI_LAS_ACT" NUMBER(10,0),
	"DDLI_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"DDLI_LAS_ACT_TIM" DATE,
	"DDLI_OBJ_STT" NUMBER(10,0),
	"DDLI_VERS" NUMBER(19,0) DEFAULT 0,
	"DDLI_VSBT" NUMBER(10,0),
	"DDLI_DLTDDT" DATE,
	"DDLI_LAS_ACT_BY" NUMBER(19,0),
	"DDLI_ORIGCRTR" NUMBER(19,0),
	"DDLI_ORIGCRTRLOGDIN" NUMBER(19,0),
	"DDLI_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"DDLI_UNIVID" VARCHAR2(4000),
	"DDLI_LBL" VARCHAR2(4000),
	"DDLI_CMMT" VARCHAR2(4000),
	"DDLI_VAL" NUMBER(10,0),
	"DDLI_SYTM" NUMBER(1,0),
	"DDLI_DDL_ITEMCONSID" NUMBER(19,0),
	"DDLI_FRSTATVD" DATE,
	"DDLI_LAS_ATVD" DATE,
	"DDLI_LAS_DCTD" DATE,
	"DDLI_WKFWISTCID" VARCHAR2(4000),
	"DDLI_CNV_ID" VARCHAR2(4000),
	"DDLI_OWNRCHNDFLAG" NUMBER(1,0),
	"DDLI_OWNRCHNDCNT" NUMBER(10,0),
	"DDLI_ID" NUMBER(19,0),
	"UMTY_ID" NUMBER(19,0),
	"CPNY_ID" NUMBER(19,0),
	"PLNS_ID" NUMBER(19,0),
	"MMGY_ID" NUMBER(19,0),
	"QTYP_ID" NUMBER(19,0),
	"PTTP_PRJ_PVTNCASE" NUMBER(1,0),
	"PTTP_PRJ_PVTNCASEREQT" NUMBER(1,0),
	"PTTP_PRJ_PVTNCM_PRJ" NUMBER(1,0),
	"PTTP_PRJ_PVTNCM_PRJ_REQT" NUMBER(1,0),
	"PTTP_ID" NUMBER(19,0),
	"BMTY_ID" NUMBER(19,0),
	"NCTY_ID" NUMBER(19,0),
	"UENY_ID" NUMBER(19,0),
	"CNTP_ID" NUMBER(19,0),
	"MNTY_ID" NUMBER(19,0),
	"CTYB_MNDTAPVL" NUMBER(1,0),
	"CTYB_ID" NUMBER(19,0),
	"IMDY_ID" NUMBER(19,0),
	"TITY_ID" NUMBER(19,0),
	"TSKT_RCPTTYP" NUMBER(10,0),
	"TSKT_ID" NUMBER(19,0),
	"PIQT_ID" NUMBER(19,0),
	"LLTP_ID" NUMBER(19,0),
	"LTTP_MNTYGKPRREVW" NUMBER(1,0),
	"LTTP_ID" NUMBER(19,0),
	"CBTY_ID" NUMBER(19,0),
	"LHTP_ID" NUMBER(19,0),
	"CDTP_ID" NUMBER(19,0),
	"FCTP_ID" NUMBER(19,0),
	"RPTY_ID" NUMBER(19,0),
	"BPTP_ID" NUMBER(19,0),
	"CCTP_ID" NUMBER(19,0),
	"ATTP_ID" NUMBER(19,0),
	"EUCY_ID" NUMBER(19,0),
	"ETTP_ID" NUMBER(19,0),
	"PRNY_ID" NUMBER(19,0),
	"DDLI_LAS_DCTDBY" NUMBER(19,0),
	"DDLI_FRSTATVDBY" NUMBER(19,0),
	"DDLI_LAS_ATVDBY" NUMBER(19,0),
	"DDLI_RATNAPVL" NUMBER(19,0),
	"DDLI_RFNGWKFWTSK" NUMBER(19,0),
	"DDLI_PRVSRFNGTSK" NUMBER(19,0),
	"DDLI_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"DDLI_OWNR" NUMBER(19,0),
	"DDLI_PRVSOWNR" NUMBER(19,0),
	"DDLI_PRVSSNDR" NUMBER(19,0),
	"DDLI_PRVSOWNRPRMN" NUMBER(19,0),
	"DDLI_TNFR" NUMBER(19,0),
	"DDLI_PRVSTNFR" NUMBER(19,0),
	"ATTP_DSCM" NUMBER(19,0),
	"CCTP_DFLTLDNGMSG" NUMBER(19,0),
	"TSKT_ICON" NUMBER(19,0),
	"DDLI_PRNT" NUMBER(19,0),
	"ATTP_DFLTLTR_HEAD" NUMBER(19,0),
	"DDLI_DDL" NUMBER(19,0),
	"STNT_ID" NUMBER(19,0),
	"CAREPLAN_NOTE_ID" NUMBER(19,0),
	"DDLI_CODE_VALUE" VARCHAR2(255 CHAR),
	"DDLI_REFERENCE" VARCHAR2(4000 CHAR)
   ) ;


  CREATE TABLE "THH_C4C"."T_NOTE"
   (	"CLASSTYPE" VARCHAR2(255),
	"NOTE_C4C_ID" VARCHAR2(4000),
	"NOTE_CRTD" DATE,
	"NOTE_LAS_ACT" NUMBER(10,0),
	"NOTE_LAS_ACT_ACTRTYP" NUMBER(10,0),
	"NOTE_LAS_ACT_TIM" DATE,
	"NOTE_OBJ_STT" NUMBER(10,0),
	"NOTE_VERS" NUMBER(19,0) DEFAULT 0,
	"NOTE_VSBT" NUMBER(10,0),
	"NOTE_DLTDDT" DATE,
	"NOTE_LAS_ACT_BY" NUMBER(19,0),
	"NOTE_ORIGCRTR" NUMBER(19,0),
	"NOTE_ORIGCRTRLOGDIN" NUMBER(19,0),
	"NOTE_LAS_ACT_BY_LOGDIN" NUMBER(19,0),
	"NOTE_UNIVID" VARCHAR2(4000),
	"NOTE_TXT" CLOB,
	"NOTE_SUBJ" CLOB,
	"NOTE_GRVCNOTE" VARCHAR2(4000),
	"NOTE_PHNENOTE" NUMBER(1,0),
	"NOTE_CALLDT_TIM" DATE,
	"NOTE_CALLDRTN" NUMBER(10,0),
	"NOTE_CALR" VARCHAR2(4000),
	"NOTE_CALLRCPT" VARCHAR2(4000),
	"NOTE_NMBRDLED" VARCHAR2(4000),
	"NOTE_ERR_CMMT" VARCHAR2(4000),
	"NOTE_RSTNCMMT" VARCHAR2(4000),
	"NOTE_WKFWISTCID" VARCHAR2(4000),
	"NOTE_CNV_ID" VARCHAR2(4000),
	"NOTE_OWNRCHNDFLAG" NUMBER(1,0),
	"NOTE_OWNRCHNDCNT" NUMBER(10,0),
	"NOTE_MRKDAS_GRVC" DATE,
	"NOTE_RSLD" DATE,
	"NOTE_ID" NUMBER(19,0),
	"NOTE_RFNGWKFWTSK" NUMBER(19,0),
	"NOTE_PRVSRFNGTSK" NUMBER(19,0),
	"NOTE_PRVSRFNGTSK_PRMN" NUMBER(19,0),
	"NOTE_OWNR" NUMBER(19,0),
	"NOTE_PRVSOWNR" NUMBER(19,0),
	"NOTE_PRVSSNDR" NUMBER(19,0),
	"NOTE_PRVSOWNRPRMN" NUMBER(19,0),
	"NOTE_TNFR" NUMBER(19,0),
	"NOTE_PRVSTNFR" NUMBER(19,0),
	"NOTE_MRKDRSLDBY" NUMBER(19,0),
	"NOTE_MRKDGRVCBY" NUMBER(19,0),
	"NOTE_CM_BASE" NUMBER(19,0),
	"NOTE_RLTDPVDR" NUMBER(19,0),
	"NOTE_UM_NOTETYP" NUMBER(19,0),
	"NOTE_PVDRNOTETYP" NUMBER(19,0),
	"NOTE_UM_EXTN" NUMBER(19,0),
	"NOTE_UM_BASENOTE" NUMBER(19,0),
	"NOTE_ATCDPVDR" NUMBER(19,0),
	"NOTE_NOTEDGIS" NUMBER(19,0),
	"NOTE_CSTMFLDS" NUMBER(19,0),
	"NOTE_PITY" NUMBER(19,0),
	"NOTE_CALLDRTNUNTS" NUMBER(19,0),
	"NOTE_CM_NOTETYP" NUMBER(19,0),
	"NOTE_CASENOTETYP" NUMBER(19,0),
	"NOTE_MEMBNOTETYP" NUMBER(19,0),
	"NOTE_MDCLSRVC" NUMBER(19,0),
	"NOTE_MEMB" NUMBER(19,0),
	"NOTE_GRP" NUMBER(19,0),
	"NOTE_SETK" NUMBER(19,0),
	"NOTE_SETK_NOTETYP" NUMBER(19,0),
	"NOTE_CAREPLAN_NOTETYPE" NUMBER(19,0),
	"NOTE_SOURCE" NUMBER(19,0),
	"NOTE_REASON" NUMBER(19,0),
	"NOTE_OUTCOME_ATTEMPT" NUMBER(19,0),
	"NOTE_CALL_OUTCOME" NUMBER(19,0),
	"NOTE_CALL_DISPOSITION" NUMBER(19,0),
	"NOTE_CONTACT_ID" NUMBER(19,0),
	"AFFILIATION_ID" NUMBER(19,0),
	"AFFILIATION_TYPE" VARCHAR2(255),
	"MEMBER_ID" NUMBER(19,0),
	"NOTE_TYPE" NUMBER(19,0),
	"NOTE_CLINICALDATAENTRY_ID" NUMBER(19,0),
	"NOTE_TAKNASMT" NUMBER(19,0),
	"ASSESSMENT_NOTE_TYPE" NUMBER(19,0),
	"NOTE_TASK_COMPLETION" NUMBER(19,0),
	"TASK_COMPLETION_NOTE_TYPE" NUMBER(19,0)
   ) ;


  CREATE INDEX "THH_C4C"."IX_ATTP_DFLTLTR_HEAD" ON "THH_C4C"."T_DDL_ITEM" ("ATTP_DFLTLTR_HEAD")
  ;


  CREATE INDEX "THH_C4C"."IX_ATTP_DSCM" ON "THH_C4C"."T_DDL_ITEM" ("ATTP_DSCM")
  ;


  CREATE INDEX "THH_C4C"."IX_CAREPLAN_NOTE_ID_DDLI_ID" ON "THH_C4C"."T_DDL_ITEM" ("CAREPLAN_NOTE_ID", "DDLI_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_CCTP_DFLTLDNGMSG" ON "THH_C4C"."T_DDL_ITEM" ("CCTP_DFLTLDNGMSG")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_CLASSTYPE" ON "THH_C4C"."T_DDL_ITEM" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_CRTD" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_DDL" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_DDL")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_FRSTATVDBY" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_FRSTATVDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_LAS_ATVDBY" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_LAS_ATVDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_LAS_DCTDBY" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_LAS_DCTDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_OBJ_STT" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_OWNR" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRNT_ID" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRNT", "DDLI_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRVSOWNR" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRVSOWNRPRMN" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRVSRFNGTSK" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRVSRFNGTSK_PRMN" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRVSSNDR" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_PRVSTNFR" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_RATNAPVL" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_RATNAPVL")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_RFNGWKFWTSK" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_TNFR" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_TNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_DDLI_UNIVID" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_ATCDPVDR" ON "THH_C4C"."T_NOTE" ("NOTE_ATCDPVDR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_BASENOTE_NID_CT_NCRTD" ON "THH_C4C"."T_NOTE" ("NOTE_UM_BASENOTE", "NOTE_CRTD", "CLASSTYPE", "NOTE_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CALLDRTNUNTS" ON "THH_C4C"."T_NOTE" ("NOTE_CALLDRTNUNTS")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CASENOTETYP" ON "THH_C4C"."T_NOTE" ("NOTE_CASENOTETYP")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CLASSTYPE" ON "THH_C4C"."T_NOTE" ("CLASSTYPE")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CLINICALDATAENTRY_ID" ON "THH_C4C"."T_NOTE" ("NOTE_CLINICALDATAENTRY_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CM_BASE" ON "THH_C4C"."T_NOTE" ("NOTE_CM_BASE")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CM_NOTETYP" ON "THH_C4C"."T_NOTE" ("NOTE_CM_NOTETYP")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CRTD" ON "THH_C4C"."T_NOTE" ("NOTE_CRTD")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_CSTMFLDS" ON "THH_C4C"."T_NOTE" ("NOTE_CSTMFLDS")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_GRP" ON "THH_C4C"."T_NOTE" ("NOTE_GRP")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_MDCLSRVC" ON "THH_C4C"."T_NOTE" ("NOTE_MDCLSRVC")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_MDCLSRVC_NID_CT_NCRTD" ON "THH_C4C"."T_NOTE" ("NOTE_MDCLSRVC", "NOTE_CRTD", "CLASSTYPE", "NOTE_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_MEMB" ON "THH_C4C"."T_NOTE" ("NOTE_MEMB")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_MEMBNOTETYP" ON "THH_C4C"."T_NOTE" ("NOTE_MEMBNOTETYP")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_MRKDGRVCBY" ON "THH_C4C"."T_NOTE" ("NOTE_MRKDGRVCBY")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_MRKDRSLDBY" ON "THH_C4C"."T_NOTE" ("NOTE_MRKDRSLDBY")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_NOTEDGIS" ON "THH_C4C"."T_NOTE" ("NOTE_NOTEDGIS")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_NOTEDGIS_NID_CT_NCRTD" ON "THH_C4C"."T_NOTE" ("NOTE_NOTEDGIS", "NOTE_CRTD", "CLASSTYPE", "NOTE_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_OBJ_STT" ON "THH_C4C"."T_NOTE" ("NOTE_OBJ_STT")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_OWNR" ON "THH_C4C"."T_NOTE" ("NOTE_OWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PITY" ON "THH_C4C"."T_NOTE" ("NOTE_PITY")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PRVSOWNR" ON "THH_C4C"."T_NOTE" ("NOTE_PRVSOWNR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PRVSOWNRPRMN" ON "THH_C4C"."T_NOTE" ("NOTE_PRVSOWNRPRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PRVSRFNGTSK" ON "THH_C4C"."T_NOTE" ("NOTE_PRVSRFNGTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PRVSRFNGTSK_PRMN" ON "THH_C4C"."T_NOTE" ("NOTE_PRVSRFNGTSK_PRMN")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PRVSSNDR" ON "THH_C4C"."T_NOTE" ("NOTE_PRVSSNDR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PRVSTNFR" ON "THH_C4C"."T_NOTE" ("NOTE_PRVSTNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_PVDRNOTETYP" ON "THH_C4C"."T_NOTE" ("NOTE_PVDRNOTETYP")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_RFNGWKFWTSK" ON "THH_C4C"."T_NOTE" ("NOTE_RFNGWKFWTSK")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_RLTDPVDR" ON "THH_C4C"."T_NOTE" ("NOTE_RLTDPVDR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_SETK_NID_CT_NCRTD" ON "THH_C4C"."T_NOTE" ("NOTE_SETK", "NOTE_CRTD", "CLASSTYPE", "NOTE_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_TNFR" ON "THH_C4C"."T_NOTE" ("NOTE_TNFR")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_UM_BASENOTE" ON "THH_C4C"."T_NOTE" ("NOTE_UM_BASENOTE")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_UM_EXTN" ON "THH_C4C"."T_NOTE" ("NOTE_UM_EXTN")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_UM_NOTETYP" ON "THH_C4C"."T_NOTE" ("NOTE_UM_NOTETYP")
  ;


  CREATE INDEX "THH_C4C"."IX_NOTE_UNIVID" ON "THH_C4C"."T_NOTE" ("NOTE_UNIVID")
  ;


  CREATE INDEX "THH_C4C"."IX_STNT_ID_DDLI_ID" ON "THH_C4C"."T_DDL_ITEM" ("STNT_ID", "DDLI_ID")
  ;


  CREATE INDEX "THH_C4C"."IX_TSKT_ICON" ON "THH_C4C"."T_DDL_ITEM" ("TSKT_ICON")
  ;


  CREATE INDEX "THH_C4C"."IX_TSKT_RCPTTYP" ON "THH_C4C"."T_DDL_ITEM" ("TSKT_RCPTTYP")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_DDL_ITEM" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."PK_T_NOTE" ON "THH_C4C"."T_NOTE" ("NOTE_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."SYS_IL0000116466C00016$$" ON "THH_C4C"."T_NOTE" (
  ;


  CREATE UNIQUE INDEX "THH_C4C"."SYS_IL0000116466C00017$$" ON "THH_C4C"."T_NOTE" (
  ;


  CREATE INDEX "THH_C4C"."T_DDL_ITEM_IX_DDLI_LBL" ON "THH_C4C"."T_DDL_ITEM" ("DDLI_LBL")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_ATTP" ON "THH_C4C"."T_DDL_ITEM" ("ATTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_BMTY" ON "THH_C4C"."T_DDL_ITEM" ("BMTY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_BPTP" ON "THH_C4C"."T_DDL_ITEM" ("BPTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CBTY" ON "THH_C4C"."T_DDL_ITEM" ("CBTY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CCTP" ON "THH_C4C"."T_DDL_ITEM" ("CCTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CDTP" ON "THH_C4C"."T_DDL_ITEM" ("CDTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CNTP" ON "THH_C4C"."T_DDL_ITEM" ("CNTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CPNY" ON "THH_C4C"."T_DDL_ITEM" ("CPNY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_CTYB" ON "THH_C4C"."T_DDL_ITEM" ("CTYB_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_ETTP" ON "THH_C4C"."T_DDL_ITEM" ("ETTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_EUCY" ON "THH_C4C"."T_DDL_ITEM" ("EUCY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_FCTP" ON "THH_C4C"."T_DDL_ITEM" ("FCTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_IMDY" ON "THH_C4C"."T_DDL_ITEM" ("IMDY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_LHTP" ON "THH_C4C"."T_DDL_ITEM" ("LHTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_LLTP" ON "THH_C4C"."T_DDL_ITEM" ("LLTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_LTTP" ON "THH_C4C"."T_DDL_ITEM" ("LTTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_MMGY" ON "THH_C4C"."T_DDL_ITEM" ("MMGY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_MNTY" ON "THH_C4C"."T_DDL_ITEM" ("MNTY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_NCTY" ON "THH_C4C"."T_DDL_ITEM" ("NCTY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_PIQT" ON "THH_C4C"."T_DDL_ITEM" ("PIQT_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_PLNS" ON "THH_C4C"."T_DDL_ITEM" ("PLNS_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_PRNY" ON "THH_C4C"."T_DDL_ITEM" ("PRNY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_PTTP" ON "THH_C4C"."T_DDL_ITEM" ("PTTP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_QTYP" ON "THH_C4C"."T_DDL_ITEM" ("QTYP_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_RPTY" ON "THH_C4C"."T_DDL_ITEM" ("RPTY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_TITY" ON "THH_C4C"."T_DDL_ITEM" ("TITY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_TSKT" ON "THH_C4C"."T_DDL_ITEM" ("TSKT_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_UENY" ON "THH_C4C"."T_DDL_ITEM" ("UENY_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C"."UK_UMTY" ON "THH_C4C"."T_DDL_ITEM" ("UMTY_ID")
  ;


  CREATE TABLE "THH_C4C_DW"."DW_DIM_NOTE"
   (	"NOTE_ID" NUMBER(19,0),
	"C4C_ID" VARCHAR2(4000),
	"CREATION_DATE" DATE,
	"MODIFIED_DATE" DATE,
	"NOTE_RECORDSTATE" VARCHAR2(255),
	"DELETION_DATE" DATE,
	"UNIVERSAL_ID" VARCHAR2(4000),
	"CALL_TIME" DATE,
	"PRIORITY" VARCHAR2(4000),
	"UMEVENT_NOTETYPE" VARCHAR2(4000),
	"CMPROGRAM_NOTETYPE" VARCHAR2(4000),
	"CASE_NOTETYPE" VARCHAR2(4000),
	"MEMBER_NOTETYPE" VARCHAR2(4000),
	"TASK_NOTETYPE" VARCHAR2(4000),
	"CALL_DURATION_UNITS" VARCHAR2(4000),
	"PROVIDER_NOTETYPE" VARCHAR2(4000),
	"CAREPLAN_NOTETYPE" VARCHAR2(4000),
	"AFFILIATION_TYPE" VARCHAR2(11),
	"CALL_DURATION" NUMBER(10,0),
	"CALLER" VARCHAR2(4000),
	"CALL_RECIPIENT" VARCHAR2(4000),
	"NUMBER_DIALED" VARCHAR2(4000),
	"DW_MODIFIED_DATE" TIMESTAMP (9)
   ) ;


  CREATE TABLE "THH_C4C_DW"."RPT_CONSTANTS"
   (	"CLASSTYPE" VARCHAR2(255),
	"OBJ_STATE" NUMBER,
	"LBL" VARCHAR2(255)
   ) ;


  CREATE UNIQUE INDEX "THH_C4C_DW"."PK_DW_DIM_NOTE_ID" ON "THH_C4C_DW"."DW_DIM_NOTE" ("NOTE_ID")
  ;


  CREATE UNIQUE INDEX "THH_C4C_DW"."PK_RPT_CONSTANTS" ON "THH_C4C_DW"."RPT_CONSTANTS" ("CLASSTYPE", "OBJ_STATE")
  ;

